package migration

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const autoGeneratedMarkerStart = "-- ============================================================================\n-- AUTO-GENERATED FUNCTIONS (Do not modify - regenerated with --regenerate-functions)\n-- ============================================================================"
const customFunctionsMarker = "-- ============================================================================\n-- CUSTOM FUNCTIONS (Add your own functions below - these are preserved)\n-- ============================================================================"

const functionsTemplate = `-- Common Database Functions for Vorzela Migration Tool
-- This file contains reusable trigger functions
-- Auto-generated by 'vm make migration' with trigger flags
-- Safe to add your own custom functions below the CUSTOM FUNCTIONS section

-- ============================================================================
-- AUTO-GENERATED FUNCTIONS (Do not modify - regenerated with --regenerate-functions)
-- ============================================================================

-- Auto-update timestamp function
CREATE OR REPLACE FUNCTION auto_update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Soft delete protection function
CREATE OR REPLACE FUNCTION protect_soft_deleted()
RETURNS TRIGGER AS $$
BEGIN
    -- Allow if record is not deleted
    IF OLD.deleted_at IS NULL THEN
        RETURN NEW;
    END IF;
    
    -- Allow if only deleted_at is being changed (restore operation)
    IF NEW.deleted_at IS DISTINCT FROM OLD.deleted_at THEN
        RETURN NEW;
    END IF;
    
    -- Block all other updates on deleted records
    RAISE EXCEPTION 'Cannot update soft-deleted record. Restore it first by setting deleted_at = NULL.';
END;
$$ LANGUAGE plpgsql;

-- Combined: auto-update + soft delete protection
CREATE OR REPLACE FUNCTION auto_update_with_soft_delete_protection()
RETURNS TRIGGER AS $$
BEGIN
    -- Check soft delete protection first
    IF OLD.deleted_at IS NOT NULL THEN
        -- Allow if only deleted_at is being changed (restore operation)
        IF NEW.deleted_at IS DISTINCT FROM OLD.deleted_at THEN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END IF;
        -- Block all other updates on deleted records
        RAISE EXCEPTION 'Cannot update soft-deleted record. Restore it first by setting deleted_at = NULL.';
    END IF;
    
    -- Auto-update timestamp for normal updates
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Prevent hard delete (enforce soft delete only)
CREATE OR REPLACE FUNCTION prevent_hard_delete()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'Hard delete is disabled. Use soft delete: UPDATE %% SET deleted_at = CURRENT_TIMESTAMP WHERE id = %%', TG_TABLE_NAME, OLD.id;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- CUSTOM FUNCTIONS (Add your own functions below - these are preserved)
-- ============================================================================

-- Add your custom trigger functions here
-- They will be preserved when regenerating the auto-generated section above

`

// EnsureFunctionsFile creates the functions.sql file if it doesn't exist
func EnsureFunctionsFile(migrationPath string) error {
	functionsFile := filepath.Join(migrationPath, "functions.sql")

	// Check if file exists
	if _, err := os.Stat(functionsFile); err == nil {
		// File exists, don't overwrite (users may have custom functions)
		return nil
	}

	// Create functions file
	if err := os.WriteFile(functionsFile, []byte(functionsTemplate), 0644); err != nil {
		return fmt.Errorf("failed to create functions.sql: %w", err)
	}

	fmt.Printf("✓ Created functions.sql with reusable trigger functions\n")
	fmt.Printf("  💡 Add custom functions below the CUSTOM FUNCTIONS section\n")
	fmt.Printf("  💡 Apply to database: vm functions migrate\n")
	return nil
}

// RegenerateFunctions updates only the auto-generated section, preserving custom functions
func RegenerateFunctions(migrationPath string) error {
	functionsFile := filepath.Join(migrationPath, "functions.sql")

	// Read existing file
	file, err := os.Open(functionsFile)
	if err != nil {
		// File doesn't exist, create it
		return EnsureFunctionsFile(migrationPath)
	}
	defer file.Close()

	// Find custom functions section
	var customFunctions strings.Builder
	scanner := bufio.NewScanner(file)
	inCustomSection := false

	for scanner.Scan() {
		line := scanner.Text()

		// Detect custom functions section
		if strings.Contains(line, "CUSTOM FUNCTIONS") {
			inCustomSection = true
			continue
		}

		// Capture custom functions
		if inCustomSection {
			customFunctions.WriteString(line)
			customFunctions.WriteString("\n")
		}
	}

	if err := scanner.Err(); err != nil {
		return fmt.Errorf("failed to read functions.sql: %w", err)
	}

	// Get auto-generated section from template
	autoGenEndIndex := strings.Index(functionsTemplate, customFunctionsMarker)
	if autoGenEndIndex == -1 {
		return fmt.Errorf("template structure error: custom functions marker not found")
	}

	// Rebuild file: auto-generated + preserved custom functions
	newContent := functionsTemplate[:autoGenEndIndex+len(customFunctionsMarker)] + "\n" + customFunctions.String()

	// Write updated file
	if err := os.WriteFile(functionsFile, []byte(newContent), 0644); err != nil {
		return fmt.Errorf("failed to update functions.sql: %w", err)
	}

	fmt.Printf("✓ Regenerated auto-generated functions (custom functions preserved)\n")
	return nil
}
