// Code generated by vorm. DO NOT EDIT.
// Source: database introspection. Re-run: vorm generate models

package models

import (
	"database/sql/driver"
	"fmt"
)

// UserStatus is the database enum user_status.
type UserStatus string

const (
	UserStatusActive  UserStatus = "active"
	UserStatusInvited UserStatus = "invited"
	UserStatusBanned  UserStatus = "banned"
)

// AllUserStatus lists every value the database accepts, in declaration order.
func AllUserStatus() []UserStatus {
	return []UserStatus{UserStatusActive, UserStatusInvited, UserStatusBanned}
}

// Valid reports whether e is one of the declared values.
func (e UserStatus) Valid() bool {
	switch e {
	case UserStatusActive, UserStatusInvited, UserStatusBanned:
		return true
	}
	return false
}

// String implements fmt.Stringer.
func (e UserStatus) String() string { return string(e) }

// Scan implements sql.Scanner.
func (e *UserStatus) Scan(src any) error {
	switch v := src.(type) {
	case nil:
		*e = ""
		return nil
	case string:
		*e = UserStatus(v)
	case []byte:
		*e = UserStatus(v)
	default:
		return fmt.Errorf("UserStatus: cannot scan %T", src)
	}
	if !e.Valid() {
		return fmt.Errorf("UserStatus: unknown value %q", string(*e))
	}
	return nil
}

// Value implements driver.Valuer.
func (e UserStatus) Value() (driver.Value, error) {
	if e == "" {
		return nil, nil
	}
	if !e.Valid() {
		return nil, fmt.Errorf("UserStatus: unknown value %q", string(e))
	}
	return string(e), nil
}

// PostState is the database enum post_state.
type PostState string

const (
	PostStateDraft     PostState = "draft"
	PostStatePublished PostState = "published"
)

// AllPostState lists every value the database accepts, in declaration order.
func AllPostState() []PostState {
	return []PostState{PostStateDraft, PostStatePublished}
}

// Valid reports whether e is one of the declared values.
func (e PostState) Valid() bool {
	switch e {
	case PostStateDraft, PostStatePublished:
		return true
	}
	return false
}

// String implements fmt.Stringer.
func (e PostState) String() string { return string(e) }

// Scan implements sql.Scanner.
func (e *PostState) Scan(src any) error {
	switch v := src.(type) {
	case nil:
		*e = ""
		return nil
	case string:
		*e = PostState(v)
	case []byte:
		*e = PostState(v)
	default:
		return fmt.Errorf("PostState: cannot scan %T", src)
	}
	if !e.Valid() {
		return fmt.Errorf("PostState: unknown value %q", string(*e))
	}
	return nil
}

// Value implements driver.Valuer.
func (e PostState) Value() (driver.Value, error) {
	if e == "" {
		return nil, nil
	}
	if !e.Valid() {
		return nil, fmt.Errorf("PostState: unknown value %q", string(e))
	}
	return string(e), nil
}
