// Code generated by vorm. DO NOT EDIT.
// Source: database introspection. Re-run: vorm generate models

package models

import (
	"encoding/json"
	"time"

	"github.com/vorzela/vorm/query"
)

// Post maps the "posts" table.
type Post struct {
	ID        int64           `json:"id" db:"id"`
	AuthorID  int64           `json:"author_id" db:"author_id"`
	EditorID  *int64          `json:"editor_id,omitempty" db:"editor_id"`
	Title     string          `json:"title" db:"title"`
	State     PostState       `json:"state" db:"state"`
	Body      *string         `json:"body,omitempty" db:"body"`
	Metadata  json.RawMessage `json:"metadata,omitempty" db:"metadata"`
	CreatedAt time.Time       `json:"created_at" db:"created_at"`

	// Relations — populated by .With(...); never selected or written.
	Author *User `json:"author,omitempty" db:"-"`
	Editor *User `json:"editor,omitempty" db:"-"`
	Tags   []Tag `json:"tags,omitempty" db:"-"`
}

// PostTable is the table name for Post.
const PostTable = "posts"

// PostColumns gives compile-time-checked column names.
var PostColumns = struct {
	ID        string
	AuthorID  string
	EditorID  string
	Title     string
	State     string
	Body      string
	Metadata  string
	CreatedAt string
}{
	ID:        "id",
	AuthorID:  "author_id",
	EditorID:  "editor_id",
	Title:     "title",
	State:     "state",
	Body:      "body",
	Metadata:  "metadata",
	CreatedAt: "created_at",
}

// PostColumnList is the explicit projection vorm selects; wildcards are never emitted.
var PostColumnList = []string{"id", "author_id", "editor_id", "title", "state", "body", "metadata", "created_at"}

// Posts is the typed query entrypoint for "posts".
var Posts = query.Model[Post](query.Meta{
	Table:       PostTable,
	Columns:     PostColumnList,
	PrimaryKey:  "id",
	SoftDeletes: false,
	Indexes:     PostIndexes,
})

// PostIndexes mirrors the indexes that exist on "posts".
var PostIndexes = []query.IndexInfo{
	{Name: "posts_pkey", Columns: []string{"id"}, Unique: true, Primary: true, Method: "btree"},
	{Name: "posts_author_id_idx", Columns: []string{"author_id"}, Unique: false, Primary: false, Method: "btree"},
}
