// Code generated by vorm. DO NOT EDIT.
// Source: database introspection. Re-run: vorm generate models

package models

import (
	"time"

	"github.com/vorzela/vorm/query"
)

// PostTag maps the "post_tags" table.
type PostTag struct {
	ID        int64     `json:"id" db:"id"`
	PostID    int64     `json:"post_id" db:"post_id"`
	TagID     int64     `json:"tag_id" db:"tag_id"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`

	// Relations — populated by .With(...); never selected or written.
	Post *Post `json:"post,omitempty" db:"-"`
	Tag  *Tag  `json:"tag,omitempty" db:"-"`
}

// PostTagTable is the table name for PostTag.
const PostTagTable = "post_tags"

// PostTagColumns gives compile-time-checked column names.
var PostTagColumns = struct {
	ID        string
	PostID    string
	TagID     string
	CreatedAt string
}{
	ID:        "id",
	PostID:    "post_id",
	TagID:     "tag_id",
	CreatedAt: "created_at",
}

// PostTagColumnList is the explicit projection vorm selects; wildcards are never emitted.
var PostTagColumnList = []string{"id", "post_id", "tag_id", "created_at"}

// PostTags is the typed query entrypoint for "post_tags".
var PostTags = query.Model[PostTag](query.Meta{
	Table:       PostTagTable,
	Columns:     PostTagColumnList,
	PrimaryKey:  "id",
	SoftDeletes: false,
})
