// Code generated by vorm. DO NOT EDIT.
// Source: database introspection. Re-run: vorm generate models

package models

import (
	"github.com/vorzela/vorm/query"
)

// Profile maps the "profiles" table.
type Profile struct {
	ID     int64   `json:"id" db:"id"`
	UserID int64   `json:"user_id" db:"user_id"`
	Bio    *string `json:"bio,omitempty" db:"bio"`

	// Relations — populated by .With(...); never selected or written.
	User *User `json:"user,omitempty" db:"-"`
}

// ProfileTable is the table name for Profile.
const ProfileTable = "profiles"

// ProfileColumns gives compile-time-checked column names.
var ProfileColumns = struct {
	ID     string
	UserID string
	Bio    string
}{
	ID:     "id",
	UserID: "user_id",
	Bio:    "bio",
}

// ProfileColumnList is the explicit projection vorm selects; wildcards are never emitted.
var ProfileColumnList = []string{"id", "user_id", "bio"}

// Profiles is the typed query entrypoint for "profiles".
var Profiles = query.Model[Profile](query.Meta{
	Table:       ProfileTable,
	Columns:     ProfileColumnList,
	PrimaryKey:  "id",
	SoftDeletes: false,
	Indexes:     ProfileIndexes,
})

// ProfileIndexes mirrors the indexes that exist on "profiles".
var ProfileIndexes = []query.IndexInfo{
	{Name: "profiles_user_id_key", Columns: []string{"user_id"}, Unique: true, Primary: false, Method: "btree"},
}
