// Code generated by vorm. DO NOT EDIT.
// Source: database introspection. Re-run: vorm generate models

package models

import (
	"context"

	"github.com/vorzela/vorm/query"
)

// Relations are registered on package init so .With("name") resolves without
// extra wiring. Every loader batches the whole result set into a bounded
// number of queries — there is no per-row lookup.
func init() {
	query.RegisterRelation(query.Relation{
		Name: "author_posts", Kind: query.RelationHasMany, Table: "posts",
		LocalKey: "id", ForeignKey: "author_id",
	}, func(ctx context.Context, db query.DB, rows []*User) error {
		return query.LoadHasMany(ctx, db, rows, query.HasMany[User, Post]{
			Related:    Posts,
			ForeignKey: "author_id",
			ParentKey:  func(m *User) any { return m.ID },
			ChildKey:   func(r *Post) any { return r.AuthorID },
			Assign:     func(m *User, rows []Post) { m.AuthorPosts = rows },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "editor_posts", Kind: query.RelationHasMany, Table: "posts",
		LocalKey: "id", ForeignKey: "editor_id",
	}, func(ctx context.Context, db query.DB, rows []*User) error {
		return query.LoadHasMany(ctx, db, rows, query.HasMany[User, Post]{
			Related:    Posts,
			ForeignKey: "editor_id",
			ParentKey:  func(m *User) any { return m.ID },
			ChildKey:   func(r *Post) any { return r.EditorID },
			Assign:     func(m *User, rows []Post) { m.EditorPosts = rows },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "manager", Kind: query.RelationBelongsTo, Table: "users",
		LocalKey: "manager_id", ForeignKey: "id",
	}, func(ctx context.Context, db query.DB, rows []*User) error {
		return query.LoadBelongsTo(ctx, db, rows, query.BelongsTo[User, User]{
			Related:   Users,
			OwnerKey:  "id",
			ParentKey: func(m *User) any { return m.ManagerID },
			ChildKey:  func(r *User) any { return r.ID },
			Assign:    func(m *User, r *User) { m.Manager = r },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "profile", Kind: query.RelationHasOne, Table: "profiles",
		LocalKey: "id", ForeignKey: "user_id",
	}, func(ctx context.Context, db query.DB, rows []*User) error {
		return query.LoadHasMany(ctx, db, rows, query.HasMany[User, Profile]{
			Related:    Profiles,
			ForeignKey: "user_id",
			ParentKey:  func(m *User) any { return m.ID },
			ChildKey:   func(r *Profile) any { return r.UserID },
			Assign: func(m *User, rows []Profile) {
				if len(rows) > 0 {
					m.Profile = &rows[0]
				}
			},
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "users", Kind: query.RelationHasMany, Table: "users",
		LocalKey: "id", ForeignKey: "manager_id",
	}, func(ctx context.Context, db query.DB, rows []*User) error {
		return query.LoadHasMany(ctx, db, rows, query.HasMany[User, User]{
			Related:    Users,
			ForeignKey: "manager_id",
			ParentKey:  func(m *User) any { return m.ID },
			ChildKey:   func(r *User) any { return r.ManagerID },
			Assign:     func(m *User, rows []User) { m.Users = rows },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "author", Kind: query.RelationBelongsTo, Table: "users",
		LocalKey: "author_id", ForeignKey: "id",
	}, func(ctx context.Context, db query.DB, rows []*Post) error {
		return query.LoadBelongsTo(ctx, db, rows, query.BelongsTo[Post, User]{
			Related:   Users,
			OwnerKey:  "id",
			ParentKey: func(m *Post) any { return m.AuthorID },
			ChildKey:  func(r *User) any { return r.ID },
			Assign:    func(m *Post, r *User) { m.Author = r },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "editor", Kind: query.RelationBelongsTo, Table: "users",
		LocalKey: "editor_id", ForeignKey: "id",
	}, func(ctx context.Context, db query.DB, rows []*Post) error {
		return query.LoadBelongsTo(ctx, db, rows, query.BelongsTo[Post, User]{
			Related:   Users,
			OwnerKey:  "id",
			ParentKey: func(m *Post) any { return m.EditorID },
			ChildKey:  func(r *User) any { return r.ID },
			Assign:    func(m *Post, r *User) { m.Editor = r },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "tags", Kind: query.RelationBelongsToMany, Table: "tags",
		LocalKey: "id", ForeignKey: "",
		PivotTable: "post_tags", PivotLocalKey: "post_id", PivotForeignKey: "tag_id",
	}, func(ctx context.Context, db query.DB, rows []*Post) error {
		return query.LoadBelongsToMany(ctx, db, rows, query.BelongsToMany[Post, Tag]{
			Related:         Tags,
			PivotTable:      "post_tags",
			PivotParentKey:  "post_id",
			PivotRelatedKey: "tag_id",
			RelatedKey:      "id",
			ParentKey:       func(m *Post) any { return m.ID },
			ChildKey:        func(r *Tag) any { return r.ID },
			Assign:          func(m *Post, rows []Tag) { m.Tags = rows },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "user", Kind: query.RelationBelongsTo, Table: "users",
		LocalKey: "user_id", ForeignKey: "id",
	}, func(ctx context.Context, db query.DB, rows []*Profile) error {
		return query.LoadBelongsTo(ctx, db, rows, query.BelongsTo[Profile, User]{
			Related:   Users,
			OwnerKey:  "id",
			ParentKey: func(m *Profile) any { return m.UserID },
			ChildKey:  func(r *User) any { return r.ID },
			Assign:    func(m *Profile, r *User) { m.User = r },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "posts", Kind: query.RelationBelongsToMany, Table: "posts",
		LocalKey: "id", ForeignKey: "",
		PivotTable: "post_tags", PivotLocalKey: "tag_id", PivotForeignKey: "post_id",
	}, func(ctx context.Context, db query.DB, rows []*Tag) error {
		return query.LoadBelongsToMany(ctx, db, rows, query.BelongsToMany[Tag, Post]{
			Related:         Posts,
			PivotTable:      "post_tags",
			PivotParentKey:  "tag_id",
			PivotRelatedKey: "post_id",
			RelatedKey:      "id",
			ParentKey:       func(m *Tag) any { return m.ID },
			ChildKey:        func(r *Post) any { return r.ID },
			Assign:          func(m *Tag, rows []Post) { m.Posts = rows },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "post", Kind: query.RelationBelongsTo, Table: "posts",
		LocalKey: "post_id", ForeignKey: "id",
	}, func(ctx context.Context, db query.DB, rows []*PostTag) error {
		return query.LoadBelongsTo(ctx, db, rows, query.BelongsTo[PostTag, Post]{
			Related:   Posts,
			OwnerKey:  "id",
			ParentKey: func(m *PostTag) any { return m.PostID },
			ChildKey:  func(r *Post) any { return r.ID },
			Assign:    func(m *PostTag, r *Post) { m.Post = r },
		})
	})

	query.RegisterRelation(query.Relation{
		Name: "tag", Kind: query.RelationBelongsTo, Table: "tags",
		LocalKey: "tag_id", ForeignKey: "id",
	}, func(ctx context.Context, db query.DB, rows []*PostTag) error {
		return query.LoadBelongsTo(ctx, db, rows, query.BelongsTo[PostTag, Tag]{
			Related:   Tags,
			OwnerKey:  "id",
			ParentKey: func(m *PostTag) any { return m.TagID },
			ChildKey:  func(r *Tag) any { return r.ID },
			Assign:    func(m *PostTag, r *Tag) { m.Tag = r },
		})
	})

}
