// Code generated by vorm. DO NOT EDIT.
// Source: database introspection. Re-run: vorm generate models

package models

import (
	"github.com/vorzela/vorm/query"
)

// Tag maps the "tags" table.
type Tag struct {
	ID   int64  `json:"id" db:"id"`
	Name string `json:"name" db:"name"`

	// Relations — populated by .With(...); never selected or written.
	Posts []Post `json:"posts,omitempty" db:"-"`
}

// TagTable is the table name for Tag.
const TagTable = "tags"

// TagColumns gives compile-time-checked column names.
var TagColumns = struct {
	ID   string
	Name string
}{
	ID:   "id",
	Name: "name",
}

// TagColumnList is the explicit projection vorm selects; wildcards are never emitted.
var TagColumnList = []string{"id", "name"}

// Tags is the typed query entrypoint for "tags".
var Tags = query.Model[Tag](query.Meta{
	Table:       TagTable,
	Columns:     TagColumnList,
	PrimaryKey:  "id",
	SoftDeletes: false,
})
