// Code generated by vorm. DO NOT EDIT.
// Source: database introspection. Re-run: vorm generate models

package models

import (
	"time"

	"github.com/vorzela/vorm/query"
)

// User: User accounts
type User struct {
	ID          int64      `json:"id" db:"id"`
	Email       string     `json:"email" db:"email"`
	DisplayName *string    `json:"display_name,omitempty" db:"display_name"`
	Status      UserStatus `json:"status" db:"status"`
	ManagerID   *int64     `json:"manager_id,omitempty" db:"manager_id"`
	// generated by the database
	SearchVector string     `json:"search_vector" db:"search_vector"`
	CreatedAt    time.Time  `json:"created_at" db:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at" db:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at,omitempty" db:"deleted_at"`

	// Relations — populated by .With(...); never selected or written.
	AuthorPosts []Post   `json:"author_posts,omitempty" db:"-"`
	EditorPosts []Post   `json:"editor_posts,omitempty" db:"-"`
	Manager     *User    `json:"manager,omitempty" db:"-"`
	Profile     *Profile `json:"profile,omitempty" db:"-"`
	Users       []User   `json:"users,omitempty" db:"-"`
}

// UserTable is the table name for User.
const UserTable = "users"

// UserColumns gives compile-time-checked column names.
var UserColumns = struct {
	ID           string
	Email        string
	DisplayName  string
	Status       string
	ManagerID    string
	SearchVector string
	CreatedAt    string
	UpdatedAt    string
	DeletedAt    string
}{
	ID:           "id",
	Email:        "email",
	DisplayName:  "display_name",
	Status:       "status",
	ManagerID:    "manager_id",
	SearchVector: "search_vector",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DeletedAt:    "deleted_at",
}

// UserColumnList is the explicit projection vorm selects; wildcards are never emitted.
var UserColumnList = []string{"id", "email", "display_name", "status", "manager_id", "search_vector", "created_at", "updated_at", "deleted_at"}

// Users is the typed query entrypoint for "users".
var Users = query.Model[User](query.Meta{
	Table:       UserTable,
	Columns:     UserColumnList,
	PrimaryKey:  "id",
	SoftDeletes: true,
	Generated:   []string{"search_vector"},
	Indexes:     UserIndexes,
})

// UserIndexes mirrors the indexes that exist on "users".
var UserIndexes = []query.IndexInfo{
	{Name: "users_pkey", Columns: []string{"id"}, Unique: true, Primary: true, Method: "btree"},
	{Name: "users_email_key", Columns: []string{"email"}, Unique: true, Primary: false, Method: "btree"},
}
