// Code generated by vorm. DO NOT EDIT.
// Source: database introspection. Re-run: vorm generate models

package models

import "github.com/vorzela/vorm/query"

// Dialect is the database these models were generated against.
const Dialect = query.Dialect("postgres")

// init aligns the runtime placeholder style with the generated schema so
// callers never have to repeat .Dialect(...) on every query.
func init() { query.SetDefaultDialect(Dialect) }
