package generate

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/vorzela/vorm/query"
)

func emitQueries(opts *Options, stubs []StubFunc, models map[string]ModelSpec) (string, error) {
	dialect := strings.ToLower(opts.Dialect)
	driver := strings.ToLower(opts.Driver)
	if driver == "" {
		driver = "pgx"
	}

	var b strings.Builder
	b.WriteString("// Code generated by vorm generate; DO NOT EDIT.\n")
	b.WriteString("// sqlc-style: *Row / *Params types; values bound as $n/? — never SELECT *.\n")
	b.WriteString("// Models table structs: vorm generate models (DO NOT EDIT models/).\n")
	if dialect == "mysql" || dialect == "mariadb" {
		b.WriteString("// Driver: MySQL/MariaDB (? placeholders) via query.OpenMySQL\n")
	} else if driver == "pq" {
		b.WriteString("// Driver: PostgreSQL ($n) via query.OpenPostgres(..., query.WithDriver(query.PostgresPQ))\n")
	} else {
		b.WriteString("// Driver: PostgreSQL ($n) via query.OpenPostgres / pgx v5 (default)\n")
	}
	b.WriteString("// Security: parameterized SQL; SafeIdent/SafeOp; column+type checks.\n\n")
	pkg := opts.Package
	if pkg == "" {
		pkg = "gen"
	}
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	imports := map[string]bool{
		`"context"`:                      true,
		`"fmt"`:                          true,
		`"github.com/vorzela/vorm/query"`: true,
	}
	for _, st := range stubs {
		ms := resolveModel(st, models)
		if needsTimeImport(st, ms) {
			imports[`"time"`] = true
		}
	}

	b.WriteString("import (\n")
	imps := make([]string, 0, len(imports))
	for imp := range imports {
		imps = append(imps, imp)
	}
	sort.Strings(imps)
	for _, imp := range imps {
		fmt.Fprintf(&b, "\t%s\n", imp)
	}
	b.WriteString(")\n\n")
	fmt.Fprintf(&b, "const GeneratedDialect = %q\n", dialect)
	fmt.Fprintf(&b, "const GeneratedDriver = %q\n\n", driver)

	qDialect := query.DialectPostgres
	if dialect == "mysql" || dialect == "mariadb" {
		qDialect = query.DialectMySQL
	}

	// Emit Row + Params types first (sqlc-style).
	for _, st := range stubs {
		ms := resolveModel(st, models)
		if st.Pending || st.Action == "" {
			continue
		}
		switch st.Action {
		case "Get", "First":
			emitRowStruct(&b, st, ms)
			emitParamsStruct(&b, st)
		case "Create", "Update", "SoftDelete", "ForceDelete":
			emitParamsStruct(&b, st)
		}
	}

	for _, st := range stubs {
		ms := resolveModel(st, models)
		if err := validateStubColumns(st, ms); err != nil {
			return "", fmt.Errorf("%s: %w", st.Name, err)
		}

		hasParams := len(userParams(st)) > 0
		fmt.Fprintf(&b, "// %s is generated from // vorm:query in %s\n", st.Name, filepath.Base(st.File))
		sig := emitTypedSignature(st, hasParams)
		fmt.Fprintf(&b, "func %s%s {\n", st.Name, sig)

		if st.Pending || st.Action == "" {
			why := st.PendingWhy
			if why == "" {
				why = "unsupported stub body"
			}
			b.WriteString("\t_ = ctx\n\t_ = db\n")
			if hasParams {
				b.WriteString("\t_ = arg\n")
			}
			fmt.Fprintf(&b, "\treturn %s // %s\n}\n\n", pendingTypedReturn(st), why)
			continue
		}

		switch st.Action {
		case "Get", "First":
			sql, argExprs, err := compileSelectSQL(st, ms, qDialect)
			if err != nil {
				return "", fmt.Errorf("%s: %w", st.Name, err)
			}
			argExprs = bindExprs(argExprs, st, hasParams)
			constName := constSQLName(st.Name)
			fmt.Fprintf(&b, "\tconst %s = %s\n", constName, strconvQuote(sql))
			if st.Action == "First" {
				emitFirstRowBody(&b, st, ms, constName, argExprs)
			} else {
				emitGetRowBody(&b, st, ms, constName, argExprs)
			}
		case "Create":
			emitCreateBody(&b, st, ms, qDialect, hasParams)
		case "Update":
			emitUpdateBody(&b, st, ms, qDialect, hasParams)
		case "SoftDelete":
			emitSoftDeleteBody(&b, st, ms, qDialect, hasParams)
		case "ForceDelete":
			emitForceDeleteBody(&b, st, ms, qDialect, hasParams)
		default:
			fmt.Fprintf(&b, "\treturn %s\n", pendingTypedReturn(st))
		}
		b.WriteString("}\n\n")
	}
	return b.String(), nil
}

func emitTypedSignature(st StubFunc, hasParams bool) string {
	params := []string{"ctx context.Context", "db query.DB"}
	if hasParams {
		params = append(params, "arg "+paramsTypeName(st.Name))
	}
	var results string
	switch st.Action {
	case "Get":
		results = "([]" + rowTypeName(st.Name) + ", error)"
	case "First":
		results = "(*" + rowTypeName(st.Name) + ", error)"
	case "Create", "Update", "SoftDelete", "ForceDelete":
		results = "(int64, error)"
	default:
		// fall back to stub results
		res := st.Results
		if len(res) == 0 {
			res = []string{"error"}
		}
		results = "(" + strings.Join(res, ", ") + ")"
	}
	return "(" + strings.Join(params, ", ") + ") " + results
}

func pendingTypedReturn(st StubFunc) string {
	switch st.Action {
	case "Get":
		return "nil, query.ErrGeneratePending"
	case "First":
		return "nil, query.ErrGeneratePending"
	case "Create", "Update", "SoftDelete", "ForceDelete":
		return "0, query.ErrGeneratePending"
	default:
		return pendingReturn(st)
	}
}

func bindExprs(exprs []string, st StubFunc, hasParams bool) []string {
	if !hasParams {
		return exprs
	}
	out := make([]string, len(exprs))
	for i, e := range exprs {
		out[i] = bindExpr(e, st)
	}
	return out
}

func bindExpr(expr string, st StubFunc) string {
	for _, p := range userParams(st) {
		if expr == p.Name {
			return "arg." + exportIdent(p.Name)
		}
	}
	return expr
}

func emitGetRowBody(b *strings.Builder, st StubFunc, ms ModelSpec, constName string, argExprs []string) {
	rowT := rowTypeName(st.Name)
	emitQueryContext(b, constName, argExprs)
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\tdefer rows.Close()\n")
	fmt.Fprintf(b, "\tvar out []%s\n", rowT)
	b.WriteString("\tfor rows.Next() {\n")
	fmt.Fprintf(b, "\t\trow, err := scan%s(rows)\n", rowT)
	b.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n\t\tout = append(out, row)\n\t}\n")
	b.WriteString("\tif err := rows.Err(); err != nil {\n\t\treturn nil, err\n\t}\n\treturn out, nil\n")
}

func emitFirstRowBody(b *strings.Builder, st StubFunc, ms ModelSpec, constName string, argExprs []string) {
	rowT := rowTypeName(st.Name)
	emitQueryContext(b, constName, argExprs)
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\tdefer rows.Close()\n")
	b.WriteString("\tif !rows.Next() {\n\t\treturn nil, fmt.Errorf(\"vorm/gen: not found\")\n\t}\n")
	fmt.Fprintf(b, "\trow, err := scan%s(rows)\n", rowT)
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	b.WriteString("\treturn &row, nil\n")
	_ = ms
}

func resolveModel(st StubFunc, models map[string]ModelSpec) ModelSpec {
	if ms, ok := models[st.Entity]; ok {
		return ms
	}
	// strip package
	if i := strings.LastIndex(st.Entity, "."); i >= 0 {
		if ms, ok := models[st.Entity[i+1:]]; ok {
			return ms
		}
	}
	for _, ms := range models {
		if st.ModelType == ms.TypeName || st.ModelType == ms.Package+"."+ms.TypeName {
			return ms
		}
	}
	return ModelSpec{}
}

func validateStubColumns(st StubFunc, ms ModelSpec) error {
	if ms.Table == "" || len(ms.Columns) == 0 {
		return nil // can't validate without model
	}
	meta := query.Meta{Table: ms.Table, Columns: ms.Columns}
	for _, w := range st.Wheres {
		if err := meta.RequireColumn(w.Col); err != nil {
			return err
		}
	}
	for _, o := range st.Orders {
		if err := meta.RequireColumn(o.Col); err != nil {
			return err
		}
	}
	for _, c := range st.Selects {
		if err := meta.RequireColumn(c); err != nil {
			return err
		}
	}
	for _, kv := range st.CreateVals {
		if err := meta.RequireColumn(kv.Col); err != nil {
			return err
		}
	}
	for _, kv := range st.UpdateVals {
		if err := meta.RequireColumn(kv.Col); err != nil {
			return err
		}
	}
	return nil
}

func compileSelectSQL(st StubFunc, ms ModelSpec, d query.Dialect) (sql string, argExprs []string, err error) {
	if ms.Table == "" {
		return "", nil, fmt.Errorf("cannot resolve model/entity %q — run vorm generate models", st.Entity)
	}
	meta := query.Meta{Table: ms.Table, Columns: ms.Columns, SoftDeletes: ms.SoftDeletes, PrimaryKey: ms.PrimaryKey}
	ent := query.Model[struct{}](meta)
	b := ent.New().Dialect(d)
	if st.Distinct {
		b = b.Distinct()
	}
	if len(st.Selects) > 0 {
		b = b.Select(st.Selects...)
	}
	for _, w := range st.Wheres {
		lit, ok := tryLiteral(w.ArgExpr)
		if !ok {
			// use zero placeholder value for SQL shape; real expr used at call site
			lit = placeholderValue(w.ArgExpr, ms, w.Col)
		}
		if w.Op == "" || w.Op == "=" {
			b = b.Where(w.Col, lit)
		} else {
			b = b.Where(w.Col, w.Op, lit)
		}
		argExprs = append(argExprs, w.ArgExpr)
	}
	for _, o := range st.Orders {
		b = b.OrderBy(o.Col, o.Dir)
	}
	if st.Limit > 0 {
		b = b.Limit(st.Limit)
	}
	if st.Offset > 0 {
		b = b.Offset(st.Offset)
	}
	if st.Action == "First" {
		b = b.Limit(1)
	}
	sql, _, err = b.CompileSelect()
	return sql, argExprs, err
}

func tryLiteral(expr string) (any, bool) {
	switch expr {
	case "true":
		return true, true
	case "false":
		return false, true
	}
	if len(expr) >= 2 && expr[0] == '"' {
		s, err := strconvUnquote(expr)
		if err == nil {
			return s, true
		}
	}
	var n int
	if _, err := fmt.Sscanf(expr, "%d", &n); err == nil && expr == fmt.Sprintf("%d", n) {
		return n, true
	}
	return nil, false
}

func placeholderValue(expr string, ms ModelSpec, col string) any {
	for _, f := range ms.Fields {
		if f.Column == col {
			switch {
			case f.Type == "bool":
				return false
			case strings.Contains(f.Type, "int"):
				return 0
			case f.Type == "string":
				return ""
			}
		}
	}
	_ = expr
	return ""
}

func emitSignature(st StubFunc, ms ModelSpec, modelPkg string) string {
	var params []string
	for _, p := range st.Params {
		typ := rewriteType(p.Type)
		if p.Name == "" {
			params = append(params, typ)
		} else {
			params = append(params, p.Name+" "+typ)
		}
	}
	if len(params) == 0 {
		params = []string{"ctx context.Context", "db query.DB"}
	}
	res := st.Results
	if len(res) == 0 {
		res = []string{"error"}
	}
	for i := range res {
		res[i] = qualifyModelType(rewriteType(res[i]), ms, modelPkg)
	}
	return "(" + strings.Join(params, ", ") + ") (" + strings.Join(res, ", ") + ")"
}

func qualifyModelType(typ string, ms ModelSpec, modelPkg string) string {
	if ms.TypeName == "" {
		return typ
	}
	pkg := ms.Package
	if pkg == "" {
		pkg = modelPkg
	}
	if pkg == "" {
		pkg = "models"
	}
	q := pkg + "." + ms.TypeName
	switch typ {
	case ms.TypeName:
		return q
	case "*" + ms.TypeName:
		return "*" + q
	case "[]" + ms.TypeName:
		return "[]" + q
	default:
		if strings.Contains(typ, "."+ms.TypeName) || strings.HasSuffix(typ, q) {
			return typ
		}
		return typ
	}
}

func rewriteType(t string) string {
	// query.DB stays; User → keep if already qualified
	return t
}

func resultModelPkg(st StubFunc) string {
	for _, r := range st.Results {
		if strings.Contains(r, "models.") {
			return "models"
		}
	}
	return ""
}

func pendingReturn(st StubFunc) string {
	if len(st.Results) == 0 {
		return "query.ErrGeneratePending"
	}
	if len(st.Results) == 1 {
		if st.Results[0] == "error" {
			return "query.ErrGeneratePending"
		}
		return "nil, query.ErrGeneratePending"
	}
	// ([]T, error) or (*T, error) or (int64, error)
	zeros := make([]string, len(st.Results)-1)
	for i := range zeros {
		zeros[i] = zeroOf(st.Results[i])
	}
	return strings.Join(zeros, ", ") + ", query.ErrGeneratePending"
}

func zeroOf(typ string) string {
	typ = strings.TrimSpace(typ)
	if strings.HasPrefix(typ, "*") || strings.HasPrefix(typ, "[]") || strings.Contains(typ, "PageResult") {
		return "nil"
	}
	switch typ {
	case "int", "int64", "int32", "uint64":
		return "0"
	case "bool":
		return "false"
	case "string":
		return `""`
	case "error":
		return "nil"
	default:
		return "nil"
	}
}

func emitQueryContext(b *strings.Builder, constName string, argExprs []string) {
	if len(argExprs) == 0 {
		fmt.Fprintf(b, "\trows, err := db.QueryContext(ctx, %s)\n", constName)
		return
	}
	fmt.Fprintf(b, "\trows, err := db.QueryContext(ctx, %s, %s)\n", constName, joinArgs(argExprs))
}

func emitCreateBody(b *strings.Builder, st StubFunc, ms ModelSpec, d query.Dialect, hasParams bool) {
	if ms.Table == "" {
		fmt.Fprintf(b, "\treturn 0, fmt.Errorf(%q)\n", "vorm/gen: missing model for Create")
		return
	}
	cols := make([]string, len(st.CreateVals))
	exprs := make([]string, len(st.CreateVals))
	for i, kv := range st.CreateVals {
		cols[i] = kv.Col
		exprs[i] = bindExpr(kv.Expr, st)
		if !hasParams {
			exprs[i] = kv.Expr
		}
	}
	holders := placeholders(d, len(cols))
	sql := fmt.Sprintf(`INSERT INTO %s (%s) VALUES (%s)`,
		quoteIdent(d, ms.Table), quoteList(d, cols), strings.Join(holders, ", "))
	if d != query.DialectMySQL {
		sql += " RETURNING " + quoteIdent(d, orPK(ms))
		fmt.Fprintf(b, "\tconst q = %s\n", strconvQuote(sql))
		fmt.Fprintf(b, "\trow := db.QueryRowContext(ctx, q, %s)\n", joinArgs(exprs))
		b.WriteString("\tvar id int64\n\tif err := row.Scan(&id); err != nil {\n\t\treturn 0, err\n\t}\n\treturn id, nil\n")
		return
	}
	fmt.Fprintf(b, "\tconst q = %s\n", strconvQuote(sql))
	fmt.Fprintf(b, "\tres, err := db.ExecContext(ctx, q, %s)\n", joinArgs(exprs))
	b.WriteString("\tif err != nil {\n\t\treturn 0, err\n\t}\n\treturn res.LastInsertId()\n")
}

func emitUpdateBody(b *strings.Builder, st StubFunc, ms ModelSpec, d query.Dialect, hasParams bool) {
	if ms.Table == "" {
		fmt.Fprintf(b, "\treturn 0, fmt.Errorf(%q)\n", "vorm/gen: missing model for Update")
		return
	}
	var sets []string
	var exprs []string
	n := 1
	for _, kv := range st.UpdateVals {
		sets = append(sets, fmt.Sprintf("%s = %s", quoteIdent(d, kv.Col), ph(d, &n)))
		e := kv.Expr
		if hasParams {
			e = bindExpr(kv.Expr, st)
		}
		exprs = append(exprs, e)
	}
	whereSQL, whereExprs := compileWhereFragment(st.Wheres, d, &n)
	if hasParams {
		whereExprs = bindExprs(whereExprs, st, true)
	}
	sql := fmt.Sprintf("UPDATE %s SET %s", quoteIdent(d, ms.Table), strings.Join(sets, ", "))
	if whereSQL != "" {
		sql += " WHERE " + whereSQL
		exprs = append(exprs, whereExprs...)
	}
	fmt.Fprintf(b, "\tconst q = %s\n", strconvQuote(sql))
	fmt.Fprintf(b, "\tres, err := db.ExecContext(ctx, q, %s)\n", joinArgs(exprs))
	b.WriteString("\tif err != nil {\n\t\treturn 0, err\n\t}\n\treturn res.RowsAffected()\n")
}

func emitSoftDeleteBody(b *strings.Builder, st StubFunc, ms ModelSpec, d query.Dialect, hasParams bool) {
	n := 1
	idExpr := st.SoftIDExpr
	if idExpr == "" {
		idExpr = "id"
	}
	if hasParams {
		idExpr = bindExpr(idExpr, st)
	}
	sql := fmt.Sprintf(`UPDATE %s SET %s = CURRENT_TIMESTAMP WHERE %s = %s`,
		quoteIdent(d, ms.Table), quoteIdent(d, "deleted_at"), quoteIdent(d, orPK(ms)), ph(d, &n))
	fmt.Fprintf(b, "\tconst q = %s\n", strconvQuote(sql))
	fmt.Fprintf(b, "\tres, err := db.ExecContext(ctx, q, %s)\n", idExpr)
	b.WriteString("\tif err != nil {\n\t\treturn 0, err\n\t}\n\treturn res.RowsAffected()\n")
}

func emitForceDeleteBody(b *strings.Builder, st StubFunc, ms ModelSpec, d query.Dialect, hasParams bool) {
	n := 1
	idExpr := st.SoftIDExpr
	if idExpr == "" {
		idExpr = "id"
	}
	if hasParams {
		idExpr = bindExpr(idExpr, st)
	}
	sql := fmt.Sprintf(`DELETE FROM %s WHERE %s = %s`,
		quoteIdent(d, ms.Table), quoteIdent(d, orPK(ms)), ph(d, &n))
	fmt.Fprintf(b, "\tconst q = %s\n", strconvQuote(sql))
	fmt.Fprintf(b, "\tres, err := db.ExecContext(ctx, q, %s)\n", idExpr)
	b.WriteString("\tif err != nil {\n\t\treturn 0, err\n\t}\n\treturn res.RowsAffected()\n")
}

func compileWhereFragment(wheres []WhereSpec, d query.Dialect, n *int) (string, []string) {
	var parts []string
	var exprs []string
	for _, w := range wheres {
		op := w.Op
		if op == "" {
			op = "="
		}
		parts = append(parts, fmt.Sprintf("%s %s %s", quoteIdent(d, w.Col), op, ph(d, n)))
		exprs = append(exprs, w.ArgExpr)
	}
	return strings.Join(parts, " AND "), exprs
}

func modelTypeName(st StubFunc, ms ModelSpec, modelPkg string) string {
	if st.ModelType != "" {
		return qualifyModelType(rewriteType(st.ModelType), ms, modelPkg)
	}
	if ms.TypeName != "" {
		pkg := ms.Package
		if pkg == "" {
			pkg = modelPkg
		}
		if pkg == "" {
			pkg = "models"
		}
		return pkg + "." + ms.TypeName
	}
	for _, r := range st.Results {
		r = strings.TrimPrefix(r, "*")
		r = strings.TrimPrefix(r, "[]")
		if r != "error" {
			return qualifyModelType(r, ms, modelPkg)
		}
	}
	return "struct{}"
}

func joinArgs(exprs []string) string {
	if len(exprs) == 0 {
		return ""
	}
	return strings.Join(exprs, ", ")
}

func placeholders(d query.Dialect, n int) []string {
	out := make([]string, n)
	for i := 0; i < n; i++ {
		if d == query.DialectMySQL {
			out[i] = "?"
		} else {
			out[i] = fmt.Sprintf("$%d", i+1)
		}
	}
	return out
}

func ph(d query.Dialect, n *int) string {
	if d == query.DialectMySQL {
		return "?"
	}
	s := fmt.Sprintf("$%d", *n)
	*n++
	return s
}

func quoteIdent(d query.Dialect, name string) string {
	q, err := query.QuoteIdent(d, name)
	if err != nil {
		return name
	}
	return q
}

func quoteList(d query.Dialect, cols []string) string {
	parts := make([]string, len(cols))
	for i, c := range cols {
		parts[i] = quoteIdent(d, c)
	}
	return strings.Join(parts, ", ")
}

func orPK(ms ModelSpec) string {
	if ms.PrimaryKey != "" {
		return ms.PrimaryKey
	}
	return "id"
}

func constSQLName(fn string) string {
	return unexport(fn) + "SQL"
}

func unexport(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

func strconvQuote(s string) string {
	return "`" + strings.ReplaceAll(s, "`", "` + \"`\" + `") + "`"
}

func strconvUnquote(s string) (string, error) {
	if len(s) >= 2 && s[0] == '"' {
		return strings.Trim(s, `"`), nil // simple
	}
	return s, fmt.Errorf("not string")
}

// emitScanners appends scan helpers for *Row types (Get/First).
func emitScanners(b *strings.Builder, stubs []StubFunc, models map[string]ModelSpec, _ string) {
	seen := map[string]bool{}
	for _, st := range stubs {
		if st.Pending || (st.Action != "Get" && st.Action != "First") {
			continue
		}
		rowT := rowTypeName(st.Name)
		if seen[rowT] {
			continue
		}
		seen[rowT] = true
		ms := resolveModel(st, models)
		cols := resultCols(st, ms)
		fmt.Fprintf(b, "func scan%s(rows query.Rows) (%s, error) {\n", rowT, rowT)
		fmt.Fprintf(b, "\tvar row %s\n", rowT)
		var ptrs []string
		for _, col := range cols {
			field, _ := fieldForColumn(ms, col)
			ptrs = append(ptrs, "&row."+field)
		}
		fmt.Fprintf(b, "\terr := rows.Scan(%s)\n", strings.Join(ptrs, ", "))
		b.WriteString("\treturn row, err\n}\n\n")
	}
}

func scanPtrs(ms ModelSpec, cols []string) []string {
	fieldByCol := map[string]string{}
	// embedded Model
	fieldByCol["id"] = "ID"
	fieldByCol["created_at"] = "CreatedAt"
	fieldByCol["updated_at"] = "UpdatedAt"
	fieldByCol["deleted_at"] = "DeletedAt"
	for _, f := range ms.Fields {
		fieldByCol[f.Column] = f.Name
	}
	var ptrs []string
	for _, c := range cols {
		name := fieldByCol[c]
		if name == "" {
			name = exportIdent(c)
		}
		ptrs = append(ptrs, "&row."+name)
	}
	return ptrs
}
