package generate

import (
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/vorzela/vorm/query"
)

func emitQueries(opts *Options, stubs []StubFunc, models map[string]ModelSpec) (string, error) {
	dialect := strings.ToLower(opts.Dialect)
	driver := strings.ToLower(opts.Driver)
	if driver == "" {
		driver = "pgx"
	}

	qDialect := query.DialectPostgres
	if dialect == "mysql" || dialect == "mariadb" {
		qDialect = query.DialectMySQL
	}

	// The body is rendered first so the import list can reflect what it
	// actually uses instead of guessing.
	body, err := emitBody(stubs, models, qDialect)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("// Code generated by vorm generate; DO NOT EDIT.\n")
	b.WriteString("// sqlc-style: *Row / *Params types; values bound as $n/? — never SELECT *.\n")
	b.WriteString("// Models table structs: vorm generate models (DO NOT EDIT models/).\n")
	if dialect == "mysql" || dialect == "mariadb" {
		b.WriteString("// Driver: MySQL/MariaDB (? placeholders) via query.OpenMySQL\n")
	} else if driver == "pq" {
		b.WriteString("// Driver: PostgreSQL ($n) via query.OpenPostgres(..., query.WithDriver(query.PostgresPQ))\n")
	} else {
		b.WriteString("// Driver: PostgreSQL ($n) via query.OpenPostgres / pgx v5 (default)\n")
	}
	b.WriteString("// Security: parameterized SQL; SafeIdent/SafeOp; column+type checks.\n\n")
	pkg := opts.Package
	if pkg == "" {
		pkg = "gen"
	}
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	imports := map[string]bool{
		`"context"`:                       true,
		`"github.com/vorzela/vorm/query"`: true,
	}
	modelPkg := opts.ModelPackage
	if modelPkg == "" {
		modelPkg = DefaultModelPkg
	}
	for pkg, used := range map[string]bool{
		`"fmt"`:     strings.Contains(body, "fmt."),
		`"strings"`: strings.Contains(body, "strings."),
		`"time"`:    strings.Contains(body, "time."),
		// Row structs reference generated enums (models.UserStatus).
		strconv.Quote(opts.ModelImport): opts.ModelImport != "" && strings.Contains(body, modelPkg+"."),
	} {
		if used {
			imports[pkg] = true
		}
	}

	writeImports(&b, imports)
	fmt.Fprintf(&b, "const GeneratedDialect = %q\n", dialect)
	fmt.Fprintf(&b, "const GeneratedDriver = %q\n\n", driver)
	b.WriteString(body)
	return b.String(), nil
}

// writeImports emits a goimports-style block: standard library first, then a
// blank line, then everything else.
func writeImports(b *strings.Builder, imports map[string]bool) {
	// The generator only ever emits this handful of standard packages, so an
	// explicit set beats guessing from the path shape (a module named
	// "vorme2e/models" has no dot to give it away).
	stdlib := map[string]bool{
		"context": true, "database/sql": true, "errors": true, "fmt": true,
		"strings": true, "time": true,
	}
	var std, ext []string
	for imp := range imports {
		if stdlib[strings.Trim(imp, `"`)] {
			std = append(std, imp)
		} else {
			ext = append(ext, imp)
		}
	}
	sort.Strings(std)
	sort.Strings(ext)

	b.WriteString("import (\n")
	for _, imp := range std {
		fmt.Fprintf(b, "\t%s\n", imp)
	}
	if len(std) > 0 && len(ext) > 0 {
		b.WriteString("\n")
	}
	for _, imp := range ext {
		fmt.Fprintf(b, "\t%s\n", imp)
	}
	b.WriteString(")\n\n")
}

// emitBody renders the Row/Params types, the query functions and the scanners.
func emitBody(stubs []StubFunc, models map[string]ModelSpec, qDialect query.Dialect) (string, error) {
	var b strings.Builder

	// Emit Row + Params types first (sqlc-style).
	for _, st := range stubs {
		ms := resolveModel(st, models)
		if st.Pending || st.Action == "" {
			continue
		}
		if returnsRows(st.Action) {
			emitRowStruct(&b, st, ms)
		}
		emitParamsStruct(&b, st)
	}

	for _, st := range stubs {
		ms := resolveModel(st, models)
		if err := validateStubColumns(st, ms); err != nil {
			return "", fmt.Errorf("%s: %w", st.Name, err)
		}

		// Stubs that stay on the runtime builder are reported instead of
		// emitted: a generated function that always fails is worse than none,
		// and the hand-written stub is already callable.
		if st.Pending || st.Action == "" {
			fmt.Fprintf(&b, "// %s stays on the runtime builder: %s\n\n", st.Name, pendingReason(st))
			continue
		}

		hasParams := len(userParams(st)) > 0
		fmt.Fprintf(&b, "// %s is generated from // vorm:query in %s\n", st.Name, filepath.Base(st.File))
		sig := emitTypedSignature(st, hasParams)
		fmt.Fprintf(&b, "func %s%s {\n", st.Name, sig)

		var err error
		switch st.Action {
		case "Get", "First", "FirstOrFail":
			err = emitSelectBody(&b, st, ms, qDialect, hasParams)
		case "Count", "Exists":
			err = emitCountBody(&b, st, ms, qDialect, hasParams)
		case "Paginate":
			err = emitPaginateBody(&b, st, ms, qDialect, hasParams)
		case "Create":
			emitCreateBody(&b, st, ms, qDialect, hasParams)
		case "Update":
			err = emitUpdateSetBody(&b, st, ms, qDialect, hasParams, st.UpdateVals, nil, true)
		case "SoftDelete":
			err = emitSoftDeleteBody(&b, st, ms, qDialect, hasParams)
		case "Delete":
			err = emitSmartDeleteBody(&b, st, ms, qDialect, hasParams)
		case "ForceDelete":
			err = emitForceDeleteBody(&b, st, ms, qDialect, hasParams)
		case "Restore":
			err = emitRestoreBody(&b, st, ms, qDialect, hasParams)
		default:
			fmt.Fprintf(&b, "\treturn %s\n", pendingTypedReturn(st))
		}
		if err != nil {
			return "", fmt.Errorf("%s: %w", st.Name, err)
		}
		b.WriteString("}\n\n")
	}
	emitScanners(&b, stubs, models, "")
	return b.String(), nil
}

// returnsRows reports whether an action projects columns into a Row struct.
func returnsRows(action string) bool {
	switch action {
	case "Get", "First", "FirstOrFail", "Paginate":
		return true
	}
	return false
}

func pendingReason(st StubFunc) string {
	if st.PendingWhy != "" {
		return st.PendingWhy
	}
	return "unsupported stub body"
}

func emitTypedSignature(st StubFunc, hasParams bool) string {
	params := []string{"ctx context.Context", "db query.DB"}
	if hasParams {
		params = append(params, "arg "+paramsTypeName(st.Name))
	}
	var results string
	switch st.Action {
	case "Get":
		results = "([]" + rowTypeName(st.Name) + ", error)"
	case "First", "FirstOrFail":
		results = "(*" + rowTypeName(st.Name) + ", error)"
	case "Paginate":
		results = "(*query.PageResult[" + rowTypeName(st.Name) + "], error)"
	case "Exists":
		results = "(bool, error)"
	case "Count", "Create", "Update", "Delete", "SoftDelete", "ForceDelete", "Restore":
		results = "(int64, error)"
	default:
		// fall back to stub results
		res := st.Results
		if len(res) == 0 {
			res = []string{"error"}
		}
		results = "(" + strings.Join(res, ", ") + ")"
	}
	return "(" + strings.Join(params, ", ") + ") " + results
}

func pendingTypedReturn(st StubFunc) string {
	switch st.Action {
	case "Get", "First", "FirstOrFail", "Paginate":
		return "nil, query.ErrGeneratePending"
	case "Exists":
		return "false, query.ErrGeneratePending"
	case "Count", "Create", "Update", "Delete", "SoftDelete", "ForceDelete", "Restore":
		return "0, query.ErrGeneratePending"
	default:
		return pendingReturn(st)
	}
}

func bindExprs(exprs []string, st StubFunc, hasParams bool) []string {
	if !hasParams {
		return exprs
	}
	out := make([]string, len(exprs))
	for i, e := range exprs {
		out[i] = bindExpr(e, st)
	}
	return out
}

func bindExpr(expr string, st StubFunc) string {
	for _, p := range userParams(st) {
		if expr == p.Name {
			return "arg." + exportIdent(p.Name)
		}
	}
	return expr
}

func resolveModel(st StubFunc, models map[string]ModelSpec) ModelSpec {
	if ms, ok := models[st.Entity]; ok {
		return ms
	}
	// strip package
	if i := strings.LastIndex(st.Entity, "."); i >= 0 {
		if ms, ok := models[st.Entity[i+1:]]; ok {
			return ms
		}
	}
	for _, ms := range models {
		if st.ModelType == ms.TypeName || st.ModelType == ms.Package+"."+ms.TypeName {
			return ms
		}
	}
	return ModelSpec{}
}

func validateStubColumns(st StubFunc, ms ModelSpec) error {
	if ms.Table == "" || len(ms.Columns) == 0 {
		return nil // can't validate without model
	}
	meta := query.Meta{Table: ms.Table, Columns: ms.Columns}
	for _, w := range append(append([]WhereSpec(nil), st.Wheres...), st.Havings...) {
		for _, c := range w.Cols {
			if err := meta.RequireColumn(c); err != nil {
				return err
			}
		}
		if w.Col == "" {
			continue
		}
		if err := meta.RequireColumn(w.Col); err != nil {
			return err
		}
	}
	for _, g := range st.GroupBy {
		if err := meta.RequireColumn(g); err != nil {
			return err
		}
	}
	for _, o := range st.Orders {
		if err := meta.RequireColumn(o.Col); err != nil {
			return err
		}
	}
	for _, c := range st.Selects {
		if err := meta.RequireColumn(c); err != nil {
			return err
		}
	}
	for _, kv := range st.CreateVals {
		if err := meta.RequireColumn(kv.Col); err != nil {
			return err
		}
	}
	for _, kv := range st.UpdateVals {
		if err := meta.RequireColumn(kv.Col); err != nil {
			return err
		}
	}
	return nil
}

func emitSignature(st StubFunc, ms ModelSpec, modelPkg string) string {
	var params []string
	for _, p := range st.Params {
		typ := rewriteType(p.Type)
		if p.Name == "" {
			params = append(params, typ)
		} else {
			params = append(params, p.Name+" "+typ)
		}
	}
	if len(params) == 0 {
		params = []string{"ctx context.Context", "db query.DB"}
	}
	res := st.Results
	if len(res) == 0 {
		res = []string{"error"}
	}
	for i := range res {
		res[i] = qualifyModelType(rewriteType(res[i]), ms, modelPkg)
	}
	return "(" + strings.Join(params, ", ") + ") (" + strings.Join(res, ", ") + ")"
}

// qualifyModelType rewrites bare references to the model type so they resolve
// from the generated package, including inside generics
// (*query.PageResult[User] → *query.PageResult[models.User]).
func qualifyModelType(typ string, ms ModelSpec, modelPkg string) string {
	if ms.TypeName == "" {
		return typ
	}
	pkg := ms.Package
	if pkg == "" {
		pkg = modelPkg
	}
	if pkg == "" {
		pkg = DefaultModelPkg
	}
	if pkg == "gen" {
		return typ
	}

	var b strings.Builder
	for i := 0; i < len(typ); {
		if !isIdentStart(typ[i]) {
			b.WriteByte(typ[i])
			i++
			continue
		}
		j := i
		for j < len(typ) && isIdentPart(typ[j]) {
			j++
		}
		word := typ[i:j]
		qualified := i > 0 && typ[i-1] == '.'
		selector := j < len(typ) && typ[j] == '.'
		if word == ms.TypeName && !qualified && !selector {
			b.WriteString(pkg + ".")
		}
		b.WriteString(word)
		i = j
	}
	return b.String()
}

func isIdentStart(c byte) bool {
	return c == '_' || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
}

func isIdentPart(c byte) bool { return isIdentStart(c) || (c >= '0' && c <= '9') }

func rewriteType(t string) string {
	// query.DB stays; User → keep if already qualified
	return t
}

func resultModelPkg(st StubFunc) string {
	for _, r := range st.Results {
		if strings.Contains(r, "models.") {
			return "models"
		}
	}
	return ""
}

func pendingReturn(st StubFunc) string {
	if len(st.Results) == 0 {
		return "query.ErrGeneratePending"
	}
	if len(st.Results) == 1 {
		if st.Results[0] == "error" {
			return "query.ErrGeneratePending"
		}
		return "nil, query.ErrGeneratePending"
	}
	// ([]T, error) or (*T, error) or (int64, error)
	zeros := make([]string, len(st.Results)-1)
	for i := range zeros {
		zeros[i] = zeroOf(st.Results[i])
	}
	return strings.Join(zeros, ", ") + ", query.ErrGeneratePending"
}

func zeroOf(typ string) string {
	typ = strings.TrimSpace(typ)
	if strings.HasPrefix(typ, "*") || strings.HasPrefix(typ, "[]") || strings.Contains(typ, "PageResult") {
		return "nil"
	}
	switch typ {
	case "int", "int64", "int32", "uint64":
		return "0"
	case "bool":
		return "false"
	case "string":
		return `""`
	case "error":
		return "nil"
	default:
		return "nil"
	}
}

func emitQueryContext(b *strings.Builder, constName string, argExprs []string) {
	if len(argExprs) == 0 {
		fmt.Fprintf(b, "\trows, err := db.QueryContext(ctx, %s)\n", constName)
		return
	}
	fmt.Fprintf(b, "\trows, err := db.QueryContext(ctx, %s, %s)\n", constName, joinArgs(argExprs))
}

func emitCreateBody(b *strings.Builder, st StubFunc, ms ModelSpec, d query.Dialect, hasParams bool) {
	if ms.Table == "" {
		fmt.Fprintf(b, "\treturn 0, fmt.Errorf(%q)\n", "vorm/gen: missing model for Create")
		return
	}
	cols := make([]string, len(st.CreateVals))
	exprs := make([]string, len(st.CreateVals))
	for i, kv := range st.CreateVals {
		cols[i] = kv.Col
		exprs[i] = bindExpr(kv.Expr, st)
		if !hasParams {
			exprs[i] = kv.Expr
		}
	}
	holders := placeholders(d, len(cols))
	sql := fmt.Sprintf(`INSERT INTO %s (%s) VALUES (%s)`,
		quoteIdent(d, ms.Table), quoteList(d, cols), strings.Join(holders, ", "))
	if d != query.DialectMySQL {
		sql += " RETURNING " + quoteIdent(d, orPK(ms))
		fmt.Fprintf(b, "\tconst q = %s\n", strconvQuote(sql))
		fmt.Fprintf(b, "\trow := db.QueryRowContext(ctx, q, %s)\n", joinArgs(exprs))
		b.WriteString("\tvar id int64\n\tif err := row.Scan(&id); err != nil {\n\t\treturn 0, err\n\t}\n\treturn id, nil\n")
		return
	}
	fmt.Fprintf(b, "\tconst q = %s\n", strconvQuote(sql))
	fmt.Fprintf(b, "\tres, err := db.ExecContext(ctx, q, %s)\n", joinArgs(exprs))
	b.WriteString("\tif err != nil {\n\t\treturn 0, err\n\t}\n\treturn res.LastInsertId()\n")
}

// primaryKeyStub rewrites Users.SoftDelete(ctx, db, id) into a WHERE on the
// primary key so the entity-level shortcuts share the planner.
func primaryKeyStub(st StubFunc, ms ModelSpec) StubFunc {
	if st.SoftIDExpr == "" || len(st.Wheres) > 0 {
		return st
	}
	cp := st
	cp.Wheres = []WhereSpec{{Col: orPK(ms), Op: "=", ArgExpr: st.SoftIDExpr}}
	return cp
}

func emitSoftDeleteBody(b *strings.Builder, st StubFunc, ms ModelSpec, d query.Dialect, hasParams bool) error {
	if !ms.SoftDeletes {
		return fmt.Errorf("SoftDelete needs a deleted_at column on %q", ms.Table)
	}
	st = primaryKeyStub(st, ms)
	return emitUpdateSetBody(b, st, ms, d, hasParams, nil,
		[]string{quoteIdent(d, "deleted_at") + " = CURRENT_TIMESTAMP"}, true)
}

func emitRestoreBody(b *strings.Builder, st StubFunc, ms ModelSpec, d query.Dialect, hasParams bool) error {
	if !ms.SoftDeletes {
		return fmt.Errorf("Restore needs a deleted_at column on %q", ms.Table)
	}
	st = primaryKeyStub(st, ms)
	return emitUpdateSetBody(b, st, ms, d, hasParams, nil,
		[]string{quoteIdent(d, "deleted_at") + " = NULL"}, false)
}

// emitSmartDeleteBody mirrors Builder.Delete: soft when the model supports it.
func emitSmartDeleteBody(b *strings.Builder, st StubFunc, ms ModelSpec, d query.Dialect, hasParams bool) error {
	if ms.SoftDeletes && !st.WithTrashed {
		return emitSoftDeleteBody(b, st, ms, d, hasParams)
	}
	return emitForceDeleteBody(b, st, ms, d, hasParams)
}

func emitForceDeleteBody(b *strings.Builder, st StubFunc, ms ModelSpec, d query.Dialect, hasParams bool) error {
	return emitDeleteBody(b, primaryKeyStub(st, ms), ms, d, hasParams)
}

func modelTypeName(st StubFunc, ms ModelSpec, modelPkg string) string {
	if st.ModelType != "" {
		return qualifyModelType(rewriteType(st.ModelType), ms, modelPkg)
	}
	if ms.TypeName != "" {
		pkg := ms.Package
		if pkg == "" {
			pkg = modelPkg
		}
		if pkg == "" {
			pkg = "models"
		}
		return pkg + "." + ms.TypeName
	}
	for _, r := range st.Results {
		r = strings.TrimPrefix(r, "*")
		r = strings.TrimPrefix(r, "[]")
		if r != "error" {
			return qualifyModelType(r, ms, modelPkg)
		}
	}
	return "struct{}"
}

func joinArgs(exprs []string) string {
	if len(exprs) == 0 {
		return ""
	}
	return strings.Join(exprs, ", ")
}

func placeholders(d query.Dialect, n int) []string {
	out := make([]string, n)
	for i := 0; i < n; i++ {
		if d == query.DialectMySQL {
			out[i] = "?"
		} else {
			out[i] = fmt.Sprintf("$%d", i+1)
		}
	}
	return out
}

func ph(d query.Dialect, n *int) string {
	if d == query.DialectMySQL {
		return "?"
	}
	s := fmt.Sprintf("$%d", *n)
	*n++
	return s
}

func quoteIdent(d query.Dialect, name string) string {
	q, err := query.QuoteIdent(d, name)
	if err != nil {
		return name
	}
	return q
}

func quoteList(d query.Dialect, cols []string) string {
	parts := make([]string, len(cols))
	for i, c := range cols {
		parts[i] = quoteIdent(d, c)
	}
	return strings.Join(parts, ", ")
}

func orPK(ms ModelSpec) string {
	if ms.PrimaryKey != "" {
		return ms.PrimaryKey
	}
	return "id"
}

func constSQLName(fn string) string {
	return unexport(fn) + "SQL"
}

func unexport(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

func strconvQuote(s string) string {
	return "`" + strings.ReplaceAll(s, "`", "` + \"`\" + `") + "`"
}

func strconvUnquote(s string) (string, error) {
	if len(s) >= 2 && s[0] == '"' {
		return strings.Trim(s, `"`), nil // simple
	}
	return s, fmt.Errorf("not string")
}

// emitScanners appends scan helpers for *Row types (Get/First).
func emitScanners(b *strings.Builder, stubs []StubFunc, models map[string]ModelSpec, _ string) {
	seen := map[string]bool{}
	for _, st := range stubs {
		if st.Pending || !returnsRows(st.Action) {
			continue
		}
		rowT := rowTypeName(st.Name)
		if seen[rowT] {
			continue
		}
		seen[rowT] = true
		ms := resolveModel(st, models)
		cols := resultCols(st, ms)
		fmt.Fprintf(b, "func scan%s(rows query.Rows) (%s, error) {\n", rowT, rowT)
		fmt.Fprintf(b, "\tvar row %s\n", rowT)
		var ptrs []string
		for _, col := range cols {
			field, _ := fieldForColumn(ms, col)
			ptrs = append(ptrs, "&row."+field)
		}
		fmt.Fprintf(b, "\terr := rows.Scan(%s)\n", strings.Join(ptrs, ", "))
		b.WriteString("\treturn row, err\n}\n\n")
	}
}

func scanPtrs(ms ModelSpec, cols []string) []string {
	fieldByCol := map[string]string{}
	// embedded Model
	fieldByCol["id"] = "ID"
	fieldByCol["created_at"] = "CreatedAt"
	fieldByCol["updated_at"] = "UpdatedAt"
	fieldByCol["deleted_at"] = "DeletedAt"
	for _, f := range ms.Fields {
		fieldByCol[f.Column] = f.Name
	}
	var ptrs []string
	for _, c := range cols {
		name := fieldByCol[c]
		if name == "" {
			name = exportIdent(c)
		}
		ptrs = append(ptrs, "&row."+name)
	}
	return ptrs
}
