package generate_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/vorzela/vorm/generate"
)

func TestGenerateEmitsSQLAndTypedReturns(t *testing.T) {
	root := t.TempDir()
	qdir := filepath.Join(root, "queries")
	mdir := filepath.Join(root, "models")
	outdir := filepath.Join(root, "gen")
	if err := os.MkdirAll(qdir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(mdir, 0o755); err != nil {
		t.Fatal(err)
	}

	model := `// Code generated by vorm generate models; DO NOT EDIT.
package models

import (
	"github.com/vorzela/vorm"
	"github.com/vorzela/vorm/query"
)

type User struct {
	vorm.Model
	Email  string ` + "`" + `json:"email" db:"email"` + "`" + `
	Name   string ` + "`" + `json:"name" db:"name"` + "`" + `
	Active bool   ` + "`" + `json:"active" db:"active"` + "`" + `
	Age    int    ` + "`" + `json:"age" db:"age"` + "`" + `
}

var Users = query.Model[User](query.Meta{
	Table: "users",
	Columns: []string{
		"id", "email", "name", "active", "age",
		"created_at", "updated_at", "deleted_at",
	},
	SoftDeletes: true,
})
`
	stub := `package queries

import (
	"context"

	"github.com/vorzela/vorm/query"
)

// vorm:query name=ListActiveAdults
func ListActiveAdults(ctx context.Context, db query.DB) ([]models.User, error) {
	return Users.
		Where("active", true).
		Where("age", ">", 18).
		OrderBy("name").
		Limit(10).
		Get(ctx, db)
}

// vorm:query name=GetUserByEmail
func GetUserByEmail(ctx context.Context, db query.DB, email string) (*models.User, error) {
	return Users.Where("email", email).First(ctx, db)
}
`
	// Fix stub to use local Users without models import path issues — entity Users in same package style:
	stub = `package queries

import (
	"context"

	"github.com/vorzela/vorm/query"
)

// vorm:query name=ListActiveAdults
func ListActiveAdults(ctx context.Context, db query.DB) ([]User, error) {
	return Users.
		Where("active", true).
		Where("age", ">", 18).
		OrderBy("name").
		Limit(10).
		Get(ctx, db)
}

// vorm:query name=GetUserByEmail
func GetUserByEmail(ctx context.Context, db query.DB, email string) (*User, error) {
	return Users.Where("email", email).First(ctx, db)
}
`
	_ = model
	if err := os.WriteFile(filepath.Join(mdir, "user.go"), []byte(model), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(qdir, "users.go"), []byte(stub), 0o644); err != nil {
		t.Fatal(err)
	}

	opts := &generate.Options{
		QueryDir:    qdir,
		OutDir:      outdir,
		ModelDir:    mdir,
		ModelImport: "models",
		Package:     "gen",
		Dialect:     "postgres",
		Driver:      "pgx",
	}
	res, err := generate.Run(opts)
	if err != nil {
		t.Fatal(err)
	}
	if res.Queries != 2 {
		t.Fatalf("queries=%d", res.Queries)
	}
	body, err := os.ReadFile(filepath.Join(outdir, "queries_gen.go"))
	if err != nil {
		t.Fatal(err)
	}
	s := string(body)
	for _, want := range []string{
		"func ListActiveAdults(",
		"([]ListActiveAdultsRow, error)",
		"type ListActiveAdultsRow struct",
		"listActiveAdultsSQL",
		`"active"`,
		`"age"`,
		"func GetUserByEmail(",
		"GetUserByEmailParams",
		"(*GetUserByEmailRow, error)",
		"arg.Email",
		"scanListActiveAdultsRow",
	} {
		if !strings.Contains(s, want) {
			t.Fatalf("missing %q in:\n%s", want, s)
		}
	}
	if strings.Contains(s, "ErrGeneratePending") && strings.Contains(s, "func ListActiveAdults") {
		// ListActiveAdults must not be pending
		idx := strings.Index(s, "func ListActiveAdults")
		chunk := s[idx : idx+800]
		if strings.Contains(chunk, "ErrGeneratePending") {
			t.Fatalf("ListActiveAdults still pending:\n%s", chunk)
		}
	}
	if strings.Contains(s, "sqlc.yaml") || strings.Contains(s, "sqlc generate") {
		t.Fatal("must not emit sqlc tooling")
	}
}
