package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The committed example is a real Go package, so `go build ./...` type-checks
// everything the query generator emits.
const (
	exampleQueryDir = "../examples/queries"
	exampleModelDir = "../examples/generated/models"
	exampleOutDir   = "../examples/generated/vorm/gen"
)

func TestGeneratedQueryExampleIsUpToDate(t *testing.T) {
	dir := t.TempDir()
	res, err := Run(&Options{
		QueryDir: exampleQueryDir,
		ModelDir: exampleModelDir,
		OutDir:   dir,
		Package:  "gen",
		Dialect:  "postgres",
		Driver:   "pgx",
	})
	if err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, "queries_gen.go"))
	if err != nil {
		t.Fatal(err)
	}
	// Keep the sample header pointing at the example path.
	body := strings.Replace(string(got),
		"// Models table structs: vorm generate models (DO NOT EDIT models/).",
		"// Sample path: examples/generated/ — real apps use ./vorm/gen/queries_gen.go",
		1)

	golden := filepath.Join(exampleOutDir, "queries_gen.go")
	if *updateGolden {
		if err := os.WriteFile(golden, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("updated %s (%d queries, %d runtime-only)", golden, res.Queries, len(res.Pending))
		return
	}
	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("%s missing (run: go test ./generate -update): %v", golden, err)
	}
	if string(want) != body {
		t.Errorf("%s drifted from the generator (run: go test ./generate -update)", golden)
	}
}

// userModel is the model package the stub fixtures resolve against.
const userModel = `// Code generated by vorm generate models; DO NOT EDIT.
package models

import (
	"github.com/vorzela/vorm"
	"github.com/vorzela/vorm/query"
)

type User struct {
	vorm.Model
	Email  string ` + "`json:\"email\" db:\"email\"`" + `
	Name   string ` + "`json:\"name\" db:\"name\"`" + `
	Active bool   ` + "`json:\"active\" db:\"active\"`" + `
	Age    int    ` + "`json:\"age\" db:\"age\"`" + `
}

var Users = query.Model[User](query.Meta{
	Table: "users",
	Columns: []string{
		"id", "email", "name", "active", "age",
		"created_at", "updated_at", "deleted_at",
	},
	SoftDeletes: true,
})
`

// lower runs the generator over a single stub body and returns the source of
// the emitted function.
func lower(t *testing.T, dialect, stubBody string) string {
	t.Helper()
	root := t.TempDir()
	qdir := filepath.Join(root, "queries")
	mdir := filepath.Join(root, "models")
	outdir := filepath.Join(root, "gen")
	for _, d := range []string{qdir, mdir} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(filepath.Join(mdir, "user.go"), []byte(userModel), 0o644); err != nil {
		t.Fatal(err)
	}
	src := "package queries\n\nimport (\n\t\"context\"\n\n\t\"github.com/vorzela/vorm/query\"\n)\n\n" + stubBody
	if err := os.WriteFile(filepath.Join(qdir, "q.go"), []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Run(&Options{
		QueryDir: qdir, OutDir: outdir, ModelDir: mdir,
		Package: "gen", Dialect: dialect, Driver: "pgx",
	}); err != nil {
		t.Fatalf("generate: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(outdir, "queries_gen.go"))
	if err != nil {
		t.Fatal(err)
	}
	return string(body)
}

func wants(t *testing.T, src string, want ...string) {
	t.Helper()
	for _, w := range want {
		if !strings.Contains(src, w) {
			t.Errorf("missing %q in:\n%s", w, src)
		}
	}
}

func TestLowerJoinsGroupByAndHaving(t *testing.T) {
	src := lower(t, "postgres", `
// vorm:query name=TopAuthors
func TopAuthors(ctx context.Context, db query.DB) ([]User, error) {
	return Users.New().
		Join("posts", "posts.user_id = users.id").
		Select("id", "email").
		Where("active", true).
		GroupBy("id").
		Having("age", ">", 1).
		OrderByDesc("email").
		Get(ctx, db)
}
`)
	wants(t, src,
		`INNER JOIN "posts" ON posts.user_id = users.id`,
		`SELECT "users"."id", "users"."email"`,
		`WHERE "users"."active" = $1`,
		`GROUP BY "users"."id"`,
		`HAVING "users"."age" > $2`,
		`ORDER BY "users"."email" DESC`,
	)
}

func TestLowerDynamicInBindsEveryElement(t *testing.T) {
	src := lower(t, "postgres", `
// vorm:query name=ByIDs
func ByIDs(ctx context.Context, db query.DB, ids ...any) ([]User, error) {
	return Users.Where("active", true).WhereIn("id", ids...).OrderBy("id").Get(ctx, db)
}
`)
	wants(t, src,
		"Ids []any",
		"args := make([]any, 0, 1+len(arg.Ids))",
		"query.InClause(query.DialectPostgres, `\"id\"`, len(args)+1, len(arg.Ids))",
		"for _, v := range arg.Ids {",
		"db.QueryContext(ctx, sb.String(), args...)",
	)
}

// A placeholder after a dynamic IN group cannot be numbered at generate time,
// because the group's width is only known once the slice arrives.
func TestLowerNumbersPlaceholdersAfterDynamicIn(t *testing.T) {
	src := lower(t, "postgres", `
// vorm:query name=ByIDsPaged
func ByIDsPaged(ctx context.Context, db query.DB, limit int, ids ...any) ([]User, error) {
	return Users.WhereIn("id", ids...).Limit(limit).Get(ctx, db)
}
`)
	wants(t, src,
		"sb.WriteString(query.Placeholder(query.DialectPostgres, len(args)+1))",
		"args = append(args, arg.Limit)",
	)
}

func TestLowerFixedInStaysConst(t *testing.T) {
	src := lower(t, "postgres", `
// vorm:query name=ByAges
func ByAges(ctx context.Context, db query.DB) ([]User, error) {
	return Users.WhereIn("age", 18, 21).Get(ctx, db)
}
`)
	wants(t, src, `"age" IN ($1, $2)`, "db.QueryContext(ctx, byAgesSQL, 18, 21)")
	if strings.Contains(src, "strings.Builder") {
		t.Errorf("a fixed IN list must stay a const statement:\n%s", src)
	}
}

func TestLowerSearchBindsPatternPerColumn(t *testing.T) {
	src := lower(t, "postgres", `
// vorm:query name=Search
func Search(ctx context.Context, db query.DB, q string, limit int) ([]User, error) {
	return Users.WhereSearch([]string{"name", "email"}, q).Limit(limit).Get(ctx, db)
}
`)
	wants(t, src,
		`("name" ILIKE $1 OR "email" ILIKE $2)`,
		"LIMIT $3",
		// The escaped pattern is built once and bound to both columns.
		"pattern1 := query.LikePattern(arg.Q)",
		"db.QueryContext(ctx, searchSQL, pattern1, pattern1, arg.Limit)",
	)
}

func TestLowerSearchUsesLikeOnMySQL(t *testing.T) {
	src := lower(t, "mysql", `
// vorm:query name=Search
func Search(ctx context.Context, db query.DB, q string) ([]User, error) {
	return Users.WhereSearch([]string{"name"}, q).Get(ctx, db)
}
`)
	wants(t, src, "`name` LIKE ?")
	if strings.Contains(src, "ILIKE") {
		t.Errorf("ILIKE is PostgreSQL-only:\n%s", src)
	}
}

func TestLowerCountAndExists(t *testing.T) {
	src := lower(t, "postgres", `
// vorm:query name=CountActive
func CountActive(ctx context.Context, db query.DB) (int64, error) {
	return Users.Where("active", true).Count(ctx, db)
}

// vorm:query name=HasEmail
func HasEmail(ctx context.Context, db query.DB, email string) (bool, error) {
	return Users.Where("email", email).Exists(ctx, db)
}
`)
	wants(t, src,
		`SELECT COUNT(*) FROM "users" WHERE "active" = $1 AND "deleted_at" IS NULL`,
		"func CountActive(ctx context.Context, db query.DB) (int64, error)",
		`SELECT 1 FROM "users" WHERE "email" = $1 AND "deleted_at" IS NULL LIMIT 1`,
		"func HasEmail(ctx context.Context, db query.DB, arg HasEmailParams) (bool, error)",
		"if query.IsNotFound(err) {",
	)
}

func TestLowerPaginateBindsLimitAndCounts(t *testing.T) {
	src := lower(t, "postgres", `
// vorm:query name=Page
func Page(ctx context.Context, db query.DB, page, perPage int) (*query.PageResult[User], error) {
	return Users.Where("active", true).OrderBy("id").OffsetPage(ctx, db, page, perPage)
}
`)
	wants(t, src,
		"(*query.PageResult[PageRow], error)",
		"LIMIT $2 OFFSET $3",
		"perPage, (page-1)*perPage",
		"SELECT COUNT(*)",
		"pages = int((total + int64(perPage) - 1) / int64(perPage))",
	)
	if strings.Contains(src, "ORDER BY \"id\" ASC LIMIT $2 OFFSET $3`\n\tvar total") {
		t.Error("the COUNT statement must not carry ORDER BY/LIMIT")
	}
}

func TestLowerSoftDeleteRestoreAndForceDelete(t *testing.T) {
	src := lower(t, "postgres", `
// vorm:query name=Soft
func Soft(ctx context.Context, db query.DB, id int64) (int64, error) {
	return Users.SoftDelete(ctx, db, id)
}

// vorm:query name=Restore
func Restore(ctx context.Context, db query.DB, id int64) (int64, error) {
	return Users.Where("id", id).Restore(ctx, db)
}

// vorm:query name=Force
func Force(ctx context.Context, db query.DB, id int64) (int64, error) {
	return Users.ForceDelete(ctx, db, id)
}
`)
	wants(t, src,
		`UPDATE "users" SET "deleted_at" = CURRENT_TIMESTAMP WHERE "id" = $1 AND "deleted_at" IS NULL`,
		`UPDATE "users" SET "deleted_at" = NULL WHERE "id" = $1`,
		`DELETE FROM "users" WHERE "id" = $1`,
	)
}

func TestLowerOperatorHelpersAndNullChecks(t *testing.T) {
	src := lower(t, "postgres", `
// vorm:query name=Adults
func Adults(ctx context.Context, db query.DB) ([]User, error) {
	return Users.Where("age", query.MoreThan(18)).WhereNotNull("email").OrWhere("active", true).Get(ctx, db)
}
`)
	wants(t, src, `"age" > $1`, `"email" IS NOT NULL`, `OR "active" = $2`)
}

func TestLowerLocksAndDistinct(t *testing.T) {
	src := lower(t, "postgres", `
// vorm:query name=Locked
func Locked(ctx context.Context, db query.DB, id int64) (*User, error) {
	return Users.New().Distinct().Where("id", id).LockForUpdate().First(ctx, db)
}
`)
	wants(t, src, "SELECT DISTINCT ", "FOR UPDATE")
}

func TestLowerRejectsUnknownColumn(t *testing.T) {
	root := t.TempDir()
	qdir := filepath.Join(root, "queries")
	mdir := filepath.Join(root, "models")
	for _, d := range []string{qdir, mdir} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(filepath.Join(mdir, "user.go"), []byte(userModel), 0o644); err != nil {
		t.Fatal(err)
	}
	stub := `package queries

import (
	"context"

	"github.com/vorzela/vorm/query"
)

// vorm:query name=Bad
func Bad(ctx context.Context, db query.DB) ([]User, error) {
	return Users.Where("nope", 1).Get(ctx, db)
}
`
	if err := os.WriteFile(filepath.Join(qdir, "q.go"), []byte(stub), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := Run(&Options{QueryDir: qdir, OutDir: filepath.Join(root, "gen"), ModelDir: mdir, Dialect: "postgres"})
	if err == nil {
		t.Fatal("expected an unknown-column failure at generate time")
	}
	if !strings.Contains(err.Error(), "nope") {
		t.Fatalf("error should name the column: %v", err)
	}
}

func TestLowerReportsRuntimeOnlyStubs(t *testing.T) {
	root := t.TempDir()
	qdir := filepath.Join(root, "queries")
	mdir := filepath.Join(root, "models")
	for _, d := range []string{qdir, mdir} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(filepath.Join(mdir, "user.go"), []byte(userModel), 0o644); err != nil {
		t.Fatal(err)
	}
	stub := `package queries

import (
	"context"

	"github.com/vorzela/vorm/query"
)

// vorm:query name=Eager
func Eager(ctx context.Context, db query.DB) ([]User, error) {
	return Users.Where("active", true).With("posts").Get(ctx, db)
}
`
	if err := os.WriteFile(filepath.Join(qdir, "q.go"), []byte(stub), 0o644); err != nil {
		t.Fatal(err)
	}
	res, err := Run(&Options{QueryDir: qdir, OutDir: filepath.Join(root, "gen"), ModelDir: mdir, Dialect: "postgres"})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Pending) != 1 || res.Pending[0].Name != "Eager" {
		t.Fatalf("Pending = %+v", res.Pending)
	}
	if !strings.Contains(res.Pending[0].Reason, "eager loading") {
		t.Fatalf("reason should explain why: %q", res.Pending[0].Reason)
	}
}
