package generate

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/vorzela/vorm/introspect"
	"github.com/vorzela/vorm/query"
)

const doNotEdit = "// Code generated by vorm. DO NOT EDIT.\n// Source: database introspection. Re-run: vorm generate models\n"

// SchemaOptions drives model generation from an introspected database.
type SchemaOptions struct {
	Schema         *introspect.Schema
	ModelDir       string
	Package        string
	Dialect        query.Dialect
	Overrides      TypeOverride
	NumericAsFloat bool
	// EmitRelations adds relation struct fields plus batched loaders derived
	// from foreign keys, enabling .With("posts").
	EmitRelations bool
	// EmitFunctions adds typed wrappers for stored routines.
	EmitFunctions bool
	// IncludeViews generates read models for views as well as tables.
	IncludeViews bool
}

// ModelsFromSchema writes models, enums, relations and function wrappers for an
// introspected schema. Generated files always carry a DO NOT EDIT header.
func ModelsFromSchema(opts SchemaOptions) (*ModelResult, error) {
	if opts.Schema == nil {
		return nil, fmt.Errorf("vorm/generate: SchemaOptions.Schema is required")
	}
	if opts.ModelDir == "" {
		opts.ModelDir = DefaultModelDir
	}
	if opts.Package == "" {
		opts.Package = DefaultModelPkg
	}
	if opts.Dialect == "" {
		opts.Dialect = opts.Schema.Dialect
	}
	if opts.Dialect == "" {
		opts.Dialect = query.DialectPostgres
	}
	if err := os.MkdirAll(opts.ModelDir, 0o755); err != nil {
		return nil, fmt.Errorf("vorm/generate: create model dir: %w", err)
	}

	mapper := NewTypeMapper(opts.Dialect, opts.Schema, opts.Overrides)
	mapper.NumericAsFloat = opts.NumericAsFloat

	tables := selectTables(opts.Schema, opts.IncludeViews)
	rels := planRelations(tables)
	fieldsByTable := resolveFields(tables, rels)

	res := &ModelResult{}
	for _, t := range tables {
		src, err := renderModel(opts, mapper, t, rels[t.Name], fieldsByTable[t.Name])
		if err != nil {
			return nil, err
		}
		path := filepath.Join(opts.ModelDir, FileName(t.Name))
		if err := writeGoFile(path, src); err != nil {
			return nil, err
		}
		res.Tables = append(res.Tables, t.Name)
		res.Files = append(res.Files, path)
	}

	if len(opts.Schema.Enums) > 0 {
		path := filepath.Join(opts.ModelDir, "enums_gen.go")
		if err := writeGoFile(path, renderEnums(opts)); err != nil {
			return nil, err
		}
		res.Files = append(res.Files, path)
	}

	if opts.EmitRelations && anyRelations(rels) {
		path := filepath.Join(opts.ModelDir, "relations_gen.go")
		if err := writeGoFile(path, renderRelations(opts, tables, rels, fieldsByTable)); err != nil {
			return nil, err
		}
		res.Files = append(res.Files, path)
	}

	if opts.EmitFunctions && len(opts.Schema.Functions) > 0 {
		src, ok := renderFunctions(opts, mapper)
		if ok {
			path := filepath.Join(opts.ModelDir, "functions_gen.go")
			if err := writeGoFile(path, src); err != nil {
				return nil, err
			}
			res.Files = append(res.Files, path)
		}
	}

	path := filepath.Join(opts.ModelDir, "vorm_gen.go")
	if err := writeGoFile(path, renderRuntime(opts)); err != nil {
		return nil, err
	}
	res.Files = append(res.Files, path)

	return res, nil
}

func selectTables(s *introspect.Schema, includeViews bool) []introspect.Table {
	out := make([]introspect.Table, 0, len(s.Tables))
	for _, t := range s.Tables {
		if t.IsView && !includeViews {
			continue
		}
		if len(t.Columns) == 0 {
			continue
		}
		out = append(out, t)
	}
	return out
}

// writeGoFile gofmts the source before writing so generated code is canonical.
// On a formatting error the raw source is still written to make debugging the
// generator possible.
func writeGoFile(path, src string) error {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		_ = os.WriteFile(path, []byte(src), 0o644)
		return fmt.Errorf("vorm/generate: %s is not valid Go: %w", filepath.Base(path), err)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("vorm/generate: write %s: %w", path, err)
	}
	return nil
}

// ---------- model rendering ----------

type importSet map[string]bool

func (s importSet) add(path string) {
	if path != "" {
		s[path] = true
	}
}

func (s importSet) block(extra ...string) string {
	for _, e := range extra {
		s.add(e)
	}
	if len(s) == 0 {
		return ""
	}
	std, third := []string{}, []string{}
	for p := range s {
		if strings.Contains(strings.SplitN(p, "/", 2)[0], ".") {
			third = append(third, p)
		} else {
			std = append(std, p)
		}
	}
	sort.Strings(std)
	sort.Strings(third)

	var b strings.Builder
	b.WriteString("import (\n")
	for _, p := range std {
		fmt.Fprintf(&b, "\t%q\n", p)
	}
	if len(std) > 0 && len(third) > 0 {
		b.WriteString("\n")
	}
	for _, p := range third {
		fmt.Fprintf(&b, "\t%q\n", p)
	}
	b.WriteString(")\n")
	return b.String()
}

func renderModel(opts SchemaOptions, mapper *TypeMapper, t introspect.Table, rels []relPlan, fields map[string]string) (string, error) {
	model := ModelName(t.Name)
	entity := EntityName(t.Name)
	imports := importSet{"github.com/vorzela/vorm/query": true}

	var fieldDecls, colConsts, colNames strings.Builder
	cols := make([]string, 0, len(t.Columns))
	generated := make([]string, 0)

	for _, c := range t.Columns {
		gt := mapper.Resolve(c)
		imports.add(gt.Import)
		field := fields[c.Name]

		jsonTag := c.Name
		if c.Nullable {
			jsonTag += ",omitempty"
		}
		if doc := columnDoc(c); doc != "" {
			fmt.Fprintf(&fieldDecls, "\t// %s\n", doc)
		}
		fmt.Fprintf(&fieldDecls, "\t%s %s `json:%q db:%q`\n", field, gt.Name, jsonTag, c.Name)
		fmt.Fprintf(&colConsts, "\t%s string\n", field)
		fmt.Fprintf(&colNames, "\t%s: %q,\n", field, c.Name)
		cols = append(cols, c.Name)
		if c.IsGenerated {
			generated = append(generated, c.Name)
		}
	}

	if opts.EmitRelations && len(rels) > 0 {
		fieldDecls.WriteString("\n\t// Relations — populated by .With(...); never selected or written.\n")
		for _, r := range rels {
			goType := ModelName(r.RelatedTable)
			if r.Kind == query.RelationHasMany || r.Kind == query.RelationBelongsToMany {
				goType = "[]" + goType
			} else {
				goType = "*" + goType
			}
			fmt.Fprintf(&fieldDecls, "\t%s %s `json:\"%s,omitempty\" db:\"-\"`\n", r.Field, goType, r.Name)
		}
	}

	pk := t.SinglePrimaryKey()
	if pk == "" {
		pk = "id"
	}

	var b strings.Builder
	b.WriteString(doNotEdit)
	fmt.Fprintf(&b, "\npackage %s\n\n", opts.Package)
	b.WriteString(imports.block())

	if t.Comment != "" {
		fmt.Fprintf(&b, "\n// %s: %s\n", model, t.Comment)
	} else {
		fmt.Fprintf(&b, "\n// %s maps the %q table.\n", model, t.Name)
	}
	fmt.Fprintf(&b, "type %s struct {\n%s}\n\n", model, fieldDecls.String())

	fmt.Fprintf(&b, "// %sTable is the table name for %s.\nconst %sTable = %q\n\n", model, model, model, t.Name)

	fmt.Fprintf(&b, "// %sColumns gives compile-time-checked column names.\n", model)
	fmt.Fprintf(&b, "var %sColumns = struct {\n%s}{\n%s}\n\n", model, colConsts.String(), colNames.String())

	fmt.Fprintf(&b, "// %sColumnList is the explicit projection vorm selects; wildcards are never emitted.\n", model)
	fmt.Fprintf(&b, "var %sColumnList = []string{%s}\n\n", model, quoteJoin(cols))

	fmt.Fprintf(&b, "// %s is the typed query entrypoint for %q.\n", entity, t.Name)
	fmt.Fprintf(&b, "var %s = query.Model[%s](query.Meta{\n", entity, model)
	fmt.Fprintf(&b, "\tTable:       %sTable,\n", model)
	fmt.Fprintf(&b, "\tColumns:     %sColumnList,\n", model)
	fmt.Fprintf(&b, "\tPrimaryKey:  %q,\n", pk)
	fmt.Fprintf(&b, "\tSoftDeletes: %t,\n", t.HasSoftDeletes())
	if len(generated) > 0 {
		fmt.Fprintf(&b, "\tGenerated:   []string{%s},\n", quoteJoin(generated))
	}
	if len(t.Indexes) > 0 {
		fmt.Fprintf(&b, "\tIndexes:     %sIndexes,\n", model)
	}
	b.WriteString("})\n")

	if len(t.Indexes) > 0 {
		fmt.Fprintf(&b, "\n// %sIndexes mirrors the indexes that exist on %q.\n", model, t.Name)
		fmt.Fprintf(&b, "var %sIndexes = []query.IndexInfo{\n", model)
		for _, idx := range t.Indexes {
			fmt.Fprintf(&b, "\t{Name: %q, Columns: []string{%s}, Unique: %t, Primary: %t, Method: %q",
				idx.Name, quoteJoin(idx.Columns), idx.Unique, idx.Primary, idx.Method)
			if idx.Partial {
				fmt.Fprintf(&b, ", Partial: true, Predicate: %q", idx.Predicate)
			}
			b.WriteString("},\n")
		}
		b.WriteString("}\n")
	}

	return b.String(), nil
}

func columnDoc(c introspect.Column) string {
	var parts []string
	if c.Comment != "" {
		parts = append(parts, c.Comment)
	}
	if c.IsGenerated {
		parts = append(parts, "generated by the database")
	}
	if c.HasDefault && c.Default != "" && !c.IsIdentity {
		parts = append(parts, "default "+strings.TrimSpace(c.Default))
	}
	return strings.Join(parts, "; ")
}

func uniqueName(name string, taken map[string]bool) string {
	candidate := name
	for i := 2; taken[candidate]; i++ {
		candidate = fmt.Sprintf("%s%d", name, i)
	}
	taken[candidate] = true
	return candidate
}

// ---------- enums ----------

func renderEnums(opts SchemaOptions) string {
	var b strings.Builder
	b.WriteString(doNotEdit)
	fmt.Fprintf(&b, "\npackage %s\n\n", opts.Package)
	b.WriteString("import (\n\t\"database/sql/driver\"\n\t\"fmt\"\n)\n")

	for _, e := range opts.Schema.Enums {
		name := EnumGoName(e.Name)
		origin := e.Name
		if e.Table != "" {
			origin = fmt.Sprintf("%s.%s", e.Table, e.Column)
		}
		fmt.Fprintf(&b, "\n// %s is the database enum %s.\ntype %s string\n\nconst (\n", name, origin, name)
		for _, v := range e.Values {
			fmt.Fprintf(&b, "\t%s %s = %q\n", EnumValueConst(name, v), name, v)
		}
		b.WriteString(")\n\n")

		fmt.Fprintf(&b, "// All%s lists every value the database accepts, in declaration order.\n", name)
		fmt.Fprintf(&b, "func All%s() []%s {\n\treturn []%s{", name, name, name)
		for i, v := range e.Values {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(EnumValueConst(name, v))
		}
		b.WriteString("}\n}\n\n")

		fmt.Fprintf(&b, "// Valid reports whether e is one of the declared values.\nfunc (e %s) Valid() bool {\n\tswitch e {\n\tcase ", name)
		for i, v := range e.Values {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(EnumValueConst(name, v))
		}
		b.WriteString(":\n\t\treturn true\n\t}\n\treturn false\n}\n\n")

		fmt.Fprintf(&b, "// String implements fmt.Stringer.\nfunc (e %s) String() string { return string(e) }\n\n", name)

		fmt.Fprintf(&b, "// Scan implements sql.Scanner.\nfunc (e *%s) Scan(src any) error {\n", name)
		b.WriteString("\tswitch v := src.(type) {\n\tcase nil:\n\t\t*e = \"\"\n\t\treturn nil\n")
		fmt.Fprintf(&b, "\tcase string:\n\t\t*e = %s(v)\n\tcase []byte:\n\t\t*e = %s(v)\n", name, name)
		fmt.Fprintf(&b, "\tdefault:\n\t\treturn fmt.Errorf(\"%s: cannot scan %%T\", src)\n\t}\n", name)
		fmt.Fprintf(&b, "\tif !e.Valid() {\n\t\treturn fmt.Errorf(\"%s: unknown value %%q\", string(*e))\n\t}\n\treturn nil\n}\n\n", name)

		fmt.Fprintf(&b, "// Value implements driver.Valuer.\nfunc (e %s) Value() (driver.Value, error) {\n", name)
		fmt.Fprintf(&b, "\tif e == \"\" {\n\t\treturn nil, nil\n\t}\n\tif !e.Valid() {\n\t\treturn nil, fmt.Errorf(\"%s: unknown value %%q\", string(e))\n\t}\n\treturn string(e), nil\n}\n", name)
	}
	return b.String()
}

// ---------- runtime ----------

func renderRuntime(opts SchemaOptions) string {
	var b strings.Builder
	b.WriteString(doNotEdit)
	fmt.Fprintf(&b, "\npackage %s\n\n", opts.Package)
	b.WriteString("import \"github.com/vorzela/vorm/query\"\n\n")
	b.WriteString("// Dialect is the database these models were generated against.\n")
	fmt.Fprintf(&b, "const Dialect = query.Dialect(%q)\n\n", string(opts.Dialect))
	b.WriteString("// init aligns the runtime placeholder style with the generated schema so\n")
	b.WriteString("// callers never have to repeat .Dialect(...) on every query.\n")
	b.WriteString("func init() { query.SetDefaultDialect(Dialect) }\n")
	return b.String()
}
