package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ModelOptions controls model generation from Schema Blueprints.
type ModelOptions struct {
	SchemaDir string // default ./schema/migrations
	ModelDir  string // default ./models
	Package   string // Go package name (default models)
	Module    string // optional module path comment
}

// ModelResult summarizes generated models.
type ModelResult struct {
	Tables []string
	Files  []string
}

// Models regenerates models/*.go from schema/migrations Blueprint Create calls.
func Models(opts ModelOptions) (*ModelResult, error) {
	if opts.SchemaDir == "" {
		opts.SchemaDir = DefaultSchemaDir
	}
	if opts.ModelDir == "" {
		opts.ModelDir = DefaultModelDir
	}
	if opts.Package == "" {
		opts.Package = "models"
	}
	specs, err := ParseSchemaDir(opts.SchemaDir)
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(opts.ModelDir, 0o755); err != nil {
		return nil, err
	}
	res := &ModelResult{}
	for _, spec := range specs {
		path, err := writeModel(opts.ModelDir, opts.Package, spec)
		if err != nil {
			return nil, err
		}
		res.Tables = append(res.Tables, spec.Table)
		res.Files = append(res.Files, path)
	}
	return res, nil
}

func writeModel(dir, pkg string, spec TableSpec) (string, error) {
	modelName := singularExport(spec.Table)
	entityName := exportIdent(spec.Table)
	file := filepath.Join(dir, singular(spec.Table)+".go")

	var enums strings.Builder
	for _, e := range spec.Enums {
		fmt.Fprintf(&enums, "// %s is the enum for %s.%s\n", e.Type, spec.Table, e.Column)
		fmt.Fprintf(&enums, "type %s string\n\nconst (\n", e.Type)
		for _, v := range e.Values {
			constName := e.Type + exportIdent(v)
			fmt.Fprintf(&enums, "\t%s %s = %q\n", constName, e.Type, v)
		}
		enums.WriteString(")\n\n")
	}

	var fields strings.Builder
	var cols []string
	if spec.HasID || true {
		cols = append(cols, "id")
	}
	for _, c := range spec.Columns {
		goType := c.GoType
		if c.Nullable && !strings.HasPrefix(goType, "*") && goType != "string" {
			goType = "*" + goType
		}
		field := exportIdent(c.Name)
		fmt.Fprintf(&fields, "\t%s %s `json:%q db:%q`\n", field, goType, c.Name, c.Name)
		cols = append(cols, c.Name)
	}
	if spec.Timestamps {
		cols = append(cols, "created_at", "updated_at")
	}
	if spec.SoftDeletes {
		cols = append(cols, "deleted_at")
	}

	colLit := quoteJoin(cols)
	soft := "false"
	if spec.SoftDeletes {
		soft = "true"
	}

	body := fmt.Sprintf(`// Code generated by vorm generate models; DO NOT EDIT.
// Source: schema/migrations Create(%q, …)
// Re-run: vorm generate models
package %s

import (
	"github.com/vorzela/vorm"
	"github.com/vorzela/vorm/query"
)

%s// %s maps table %q.
type %s struct {
	vorm.Model
%s}

// %s is the typed query entrypoint (explicit columns — never SELECT *).
var %s = query.Model[%s](query.Meta{
	Table:       %q,
	Columns:     []string{%s},
	SoftDeletes: %s,
})
`, spec.Table, pkg, enums.String(), modelName, spec.Table, modelName, fields.String(),
		entityName, entityName, modelName, spec.Table, colLit, soft)

	if err := os.WriteFile(file, []byte(body), 0o644); err != nil {
		return "", err
	}
	return file, nil
}

func quoteJoin(ss []string) string {
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = `"` + s + `"`
	}
	return strings.Join(parts, ", ")
}

func singular(table string) string {
	if strings.HasSuffix(table, "ies") && len(table) > 3 {
		return table[:len(table)-3] + "y"
	}
	if strings.HasSuffix(table, "s") && len(table) > 1 && !strings.HasSuffix(table, "ss") {
		return table[:len(table)-1]
	}
	return table
}

func singularExport(table string) string {
	return exportIdent(singular(table))
}
