package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/vorzela/vorm/schema"
	"github.com/vorzela/vorm/vmtool"
)

// TableOptions controls Laravel-like `vorm make table` scaffolds.
type TableOptions struct {
	Table     string
	Soft      bool
	BelongsTo []string // "column:table" e.g. user_id:users
	Strings   []string
	Texts     []string
	Enums     []string // "column:val1,val2"
	Booleans  []string
	Path      string
	Dialect   string
}

// CreateTable writes one migration for a single table and returns its path.
// Prefer this over a mega MigrateBlog() — one CLI command per table.
func CreateTable(opts TableOptions) (string, error) {
	if opts.Table == "" {
		return "", fmt.Errorf("scaffold: table name required")
	}
	if opts.Path == "" {
		opts.Path = "./migrations"
	}
	if opts.Dialect == "" {
		opts.Dialect = vmtool.DetectDialect()
	}
	if err := os.MkdirAll(opts.Path, 0o755); err != nil {
		return "", err
	}

	bp := schema.NewBlueprint(opts.Table)
	bp.ID()
	for _, s := range opts.Strings {
		bp.String(s).NotNull()
	}
	for _, s := range opts.Texts {
		bp.Text(s)
	}
	for _, b := range opts.Booleans {
		bp.Boolean(b).Default("FALSE").NotNull()
	}
	for _, e := range opts.Enums {
		col, vals, ok := strings.Cut(e, ":")
		if !ok || col == "" || vals == "" {
			return "", fmt.Errorf("scaffold: bad --enum %q (want column:a,b,c)", e)
		}
		bp.Enum(col, splitComma(vals)...)
	}
	for _, bt := range opts.BelongsTo {
		col, table, ok := strings.Cut(bt, ":")
		if !ok {
			col = bt
			table = strings.TrimSuffix(col, "_id") + "s"
		}
		bp.BelongsTo(col, table)
		bp.Index(col)
	}
	bp.Timestamps()
	if opts.Soft {
		bp.SoftDeletes()
	}

	up, down := bp.Compile(opts.Dialect)
	name := "create_" + opts.Table + "_table"
	ts := time.Now().UnixNano() / 1e6 // ms — avoid collisions when scaffolding multiple tables quickly
	filename := fmt.Sprintf("%d_%s.sql", ts, name)
	full := filepath.Join(opts.Path, filename)
	body := fmt.Sprintf(`%s
-- Migration: %s
-- Generated by vorm make table (uses vm under the hood)

-- ⬆ Up (Run when migrating forward)
%s

-- ⬇ Down (Run when rolling back)
%s
`, SuggestionHeader(opts.Table), strings.ToUpper(name), strings.TrimSpace(up), strings.TrimSpace(down))

	if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
		return "", err
	}
	return full, nil
}

func splitComma(s string) []string {
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

// SuggestionHeader guides edits after scaffold.
func SuggestionHeader(table string) string {
	return fmt.Sprintf(`-- vorm scaffold for %q
-- Next: edit columns if needed → vorm lint → vorm migrate
-- More columns later: vorm make migration alter_%s_table
-- Flags you can re-run with: --soft --belongs-to=user_id:users --string=title --enum=status:draft,published --text=body
`, table, table)
}
