package introspect

import (
	"context"
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/vorzela/vorm/query"
)

// liveURLEnv names the DSN of a server to run the catalog queries against.
// Both live tests are skipped when it is unset, so the default test run needs
// no database.
//
//	VORM_INTROSPECT_POSTGRES_URL='postgres:///postgres' go test ./introspect/...
const liveURLEnv = "VORM_INTROSPECT_POSTGRES_URL"

// liveDDLEnv opts into the fixture test, which creates and drops liveSchema.
// Point liveURLEnv at a throwaway database before setting it.
const liveDDLEnv = "VORM_INTROSPECT_POSTGRES_DDL"

const liveSchema = "vorm_introspect_live"

// liveDDL builds a schema exercising every catalog feature the introspector
// reads. %[1]s is the scratch schema name.
const liveDDL = `
DROP SCHEMA IF EXISTS %[1]s CASCADE;
CREATE SCHEMA %[1]s;

CREATE TYPE %[1]s.user_status AS ENUM ('active', 'banned');

CREATE TABLE %[1]s.users (
    id         bigserial PRIMARY KEY,
    email      varchar(255) NOT NULL UNIQUE,
    status     %[1]s.user_status NOT NULL DEFAULT 'active',
    tags       text[],
    balance    numeric(12,2),
    search     tsvector GENERATED ALWAYS AS (to_tsvector('english', email)) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT users_id_email_key UNIQUE (id, email)
);
COMMENT ON TABLE %[1]s.users IS 'app users';
COMMENT ON COLUMN %[1]s.users.email IS 'login address';
CREATE INDEX users_live_email_idx ON %[1]s.users (email) WHERE deleted_at IS NULL;
CREATE INDEX users_lower_email_idx ON %[1]s.users (lower(email));
CREATE INDEX users_tags_gin ON %[1]s.users USING gin (tags);

CREATE TABLE %[1]s.posts (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id bigint NOT NULL REFERENCES %[1]s.users (id) ON DELETE CASCADE,
    title     varchar(120) NOT NULL,
    CONSTRAINT posts_pair_fkey FOREIGN KEY (author_id, title)
        REFERENCES %[1]s.users (id, email) ON UPDATE RESTRICT ON DELETE SET NULL
);
CREATE INDEX posts_author_title_idx ON %[1]s.posts (author_id, title);
CREATE INDEX posts_author_incl_idx ON %[1]s.posts (author_id) INCLUDE (title);

CREATE TABLE %[1]s.events (id bigint, at timestamptz NOT NULL) PARTITION BY RANGE (at);
CREATE TABLE %[1]s.events_2024 PARTITION OF %[1]s.events
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

CREATE VIEW %[1]s.active_users AS
    SELECT id, email FROM %[1]s.users WHERE deleted_at IS NULL;

CREATE TABLE %[1]s.migrations (version varchar(255) PRIMARY KEY);
CREATE TABLE %[1]s.migrations_lock (id integer PRIMARY KEY);

CREATE FUNCTION %[1]s.search_users(q text, lim integer DEFAULT 10)
    RETURNS SETOF %[1]s.users LANGUAGE sql STABLE
    AS 'SELECT * FROM ' || quote_ident('%[1]s') || '.users WHERE email = $1 LIMIT $2';

CREATE PROCEDURE %[1]s.purge_users() LANGUAGE plpgsql AS $proc$ BEGIN END $proc$;
`

// TestPostgresLiveCatalogSQL checks that every catalog query parses and runs on
// the target server. It only reads, so it is safe against any database and
// catches version drift in the catalog columns the queries depend on.
func TestPostgresLiveCatalogSQL(t *testing.T) {
	ctx := context.Background()
	conn := openLive(ctx, t)
	defer conn.Close()

	// pg_catalog is dense with the shapes the queries must survive: multi-column
	// indexes, array columns and int2vector attributes.
	for _, schema := range []string{"pg_catalog", "information_schema", DefaultSchemaName} {
		t.Run(schema, func(t *testing.T) {
			s, err := Postgres(ctx, conn, Options{SchemaName: schema, IncludeViews: true})
			if err != nil {
				t.Fatalf("Postgres(%s): %v", schema, err)
			}
			for _, table := range s.Tables {
				if len(table.Columns) == 0 && !table.IsView {
					t.Errorf("%s.%s has no columns", schema, table.Name)
				}
			}
		})
	}

	// Spot-check extraction against catalog facts that are stable across
	// PostgreSQL versions.
	s, err := Postgres(ctx, conn, Options{SchemaName: "pg_catalog"})
	if err != nil {
		t.Fatalf("Postgres(pg_catalog): %v", err)
	}

	pgClass, ok := s.Table("pg_class")
	if !ok {
		t.Fatal("pg_class missing")
	}
	relname, ok := pgClass.Column("relname")
	if !ok {
		t.Fatal("pg_class.relname missing")
	}
	if relname.DBType != "name" || relname.Nullable || relname.Position <= 0 {
		t.Errorf("pg_class.relname = %+v, want a non-null, positioned name column", *relname)
	}
	if relacl, ok := pgClass.Column("relacl"); !ok {
		t.Error("pg_class.relacl missing")
	} else if !relacl.IsArray || relacl.ArrayElem != "aclitem" {
		t.Errorf("pg_class.relacl = %+v, want an aclitem array", *relacl)
	}

	pgIndex, ok := s.Table("pg_index")
	if !ok {
		t.Fatal("pg_index missing")
	}
	if indkey, ok := pgIndex.Column("indkey"); !ok {
		t.Error("pg_index.indkey missing")
	} else if indkey.DBType != "int2vector" {
		t.Errorf("pg_index.indkey DBType = %q, want int2vector", indkey.DBType)
	}

	var multiColumn, indexed int
	for _, table := range s.Tables {
		for _, idx := range table.Indexes {
			indexed++
			if len(idx.Columns) > 1 {
				multiColumn++
			}
		}
	}
	if indexed == 0 {
		t.Error("no indexes read from pg_catalog")
	}
	if multiColumn == 0 {
		t.Error("no multi-column index read from pg_catalog; indkey unnesting is likely broken")
	}
}

// TestPostgresLiveFixture builds a schema covering every feature the
// introspector reads and asserts the result end to end. It needs DDL rights and
// is opt-in via VORM_INTROSPECT_POSTGRES_DDL.
func TestPostgresLiveFixture(t *testing.T) {
	if os.Getenv(liveDDLEnv) == "" {
		t.Skipf("set %s to run the fixture test (it creates and drops schema %s)", liveDDLEnv, liveSchema)
	}
	ctx := context.Background()
	conn := openLive(ctx, t)
	defer conn.Close()

	if _, err := conn.ExecContext(ctx, fmt.Sprintf(liveDDL, liveSchema)); err != nil {
		t.Fatalf("create fixture schema: %v", err)
	}
	t.Cleanup(func() {
		if _, err := conn.ExecContext(ctx, "DROP SCHEMA IF EXISTS "+liveSchema+" CASCADE"); err != nil {
			t.Errorf("drop fixture schema: %v", err)
		}
	})

	s, err := Postgres(ctx, conn, Options{SchemaName: liveSchema, IncludeViews: true})
	if err != nil {
		t.Fatalf("Postgres: %v", err)
	}

	wantTables := []string{"active_users", "events", "posts", "users"}
	if got := tableNames(s); !equalStrings(got, wantTables) {
		t.Fatalf("tables = %v, want %v (bookkeeping excluded, partitions collapsed)", got, wantTables)
	}

	users, ok := s.Table("users")
	if !ok {
		t.Fatal("users missing")
	}
	if users.Comment != "app users" {
		t.Errorf("table comment = %q", users.Comment)
	}
	if got := users.SinglePrimaryKey(); got != "id" {
		t.Errorf("primary key = %q, want id", got)
	}
	if !users.HasTimestamps() || !users.HasSoftDeletes() {
		t.Error("users should report timestamps and soft deletes")
	}

	id, _ := users.Column("id")
	if !id.IsIdentity || !id.HasDefault || !strings.HasPrefix(id.Default, "nextval(") {
		t.Errorf("bigserial id = %+v, want identity with a nextval default", *id)
	}
	if id.DBType != "int8" {
		t.Errorf("id DBType = %q, want int8", id.DBType)
	}

	email, _ := users.Column("email")
	if email.CharMaxLen != 255 || email.Comment != "login address" || email.Nullable {
		t.Errorf("email = %+v", *email)
	}
	if email.FullType != "character varying(255)" {
		t.Errorf("email FullType = %q", email.FullType)
	}

	status, _ := users.Column("status")
	if status.EnumType != "user_status" || status.DBType != "user_status" {
		t.Errorf("status = %+v, want the enum type tagged", *status)
	}
	if !status.HasDefault {
		t.Error("status should have a default")
	}

	tags, _ := users.Column("tags")
	if !tags.IsArray || tags.ArrayElem != "text" || tags.FullType != "text[]" {
		t.Errorf("tags = %+v, want a text array", *tags)
	}

	balance, _ := users.Column("balance")
	if balance.NumPrecision != 12 || balance.NumScale != 2 {
		t.Errorf("balance precision/scale = %d/%d, want 12/2", balance.NumPrecision, balance.NumScale)
	}

	search, _ := users.Column("search")
	if !search.IsGenerated || search.HasDefault {
		t.Errorf("search generated=%v hasDefault=%v, want true/false", search.IsGenerated, search.HasDefault)
	}

	partial := findIndex(users, "users_live_email_idx")
	if !partial.Partial || !strings.Contains(partial.Predicate, "deleted_at IS NULL") {
		t.Errorf("partial index = %+v", *partial)
	}
	expr := findIndex(users, "users_lower_email_idx")
	if !expr.Expression || len(expr.Columns) != 0 {
		t.Errorf("expression index = %+v, want no plain columns", *expr)
	}
	if gin := findIndex(users, "users_tags_gin"); gin.Method != "gin" {
		t.Errorf("gin index method = %q", gin.Method)
	}

	posts, ok := s.Table("posts")
	if !ok {
		t.Fatal("posts missing")
	}
	postID, _ := posts.Column("id")
	if !postID.IsIdentity {
		t.Error("GENERATED BY DEFAULT AS IDENTITY should be reported as identity")
	}
	if got := findIndex(posts, "posts_author_title_idx").Columns; !equalStrings(got, []string{"author_id", "title"}) {
		t.Errorf("composite index columns = %v", got)
	}
	if got := findIndex(posts, "posts_author_incl_idx").Columns; !equalStrings(got, []string{"author_id"}) {
		t.Errorf("INCLUDE payload leaked into index columns: %v", got)
	}

	fk := findForeignKey(posts, "posts_pair_fkey")
	if !equalStrings(fk.Columns, []string{"author_id", "title"}) ||
		!equalStrings(fk.RefColumns, []string{"id", "email"}) {
		t.Errorf("composite fk = %v -> %v", fk.Columns, fk.RefColumns)
	}
	if fk.OnUpdate != "RESTRICT" || fk.OnDelete != "SET NULL" || fk.RefTable != "users" || fk.RefSchema != liveSchema {
		t.Errorf("composite fk metadata = %+v", *fk)
	}
	cascade := findForeignKey(posts, "posts_author_id_fkey")
	if cascade.OnDelete != "CASCADE" || cascade.OnUpdate != "NO ACTION" {
		t.Errorf("cascade fk = %+v", *cascade)
	}

	if view, ok := s.Table("active_users"); !ok || !view.IsView || !view.HasColumn("email") {
		t.Errorf("view = %+v (ok=%v)", view, ok)
	}
	if _, ok := s.Table("events_2024"); ok {
		t.Error("leaf partitions should not be reported as tables")
	}

	enum, ok := s.Enum("user_status")
	if !ok || !equalStrings(enum.Values, []string{"active", "banned"}) {
		t.Errorf("enum = %+v (ok=%v)", enum, ok)
	}

	fn := findFunction(s, "search_users")
	if fn == nil {
		t.Fatalf("search_users missing, functions = %+v", s.Functions)
	}
	if !fn.ReturnsSet || !strings.HasSuffix(fn.ReturnType, "users") || fn.Kind != "function" || fn.Language != "sql" {
		t.Errorf("function = %+v", *fn)
	}
	if len(fn.Args) != 2 {
		t.Fatalf("function args = %+v, want 2", fn.Args)
	}
	if fn.Args[0].Name != "q" || fn.Args[0].DBType != "text" || fn.Args[0].Mode != "IN" || fn.Args[0].HasDefault {
		t.Errorf("arg 0 = %+v", fn.Args[0])
	}
	if fn.Args[1].Name != "lim" || fn.Args[1].DBType != "integer" || !fn.Args[1].HasDefault {
		t.Errorf("arg 1 = %+v", fn.Args[1])
	}

	proc := findFunction(s, "purge_users")
	if proc == nil {
		t.Fatal("purge_users missing")
	}
	if proc.Kind != "procedure" || proc.ReturnType != "" || proc.Language != "plpgsql" {
		t.Errorf("procedure = %+v", *proc)
	}
}

func openLive(ctx context.Context, t *testing.T) query.Conn {
	t.Helper()
	url := os.Getenv(liveURLEnv)
	if url == "" {
		t.Skipf("set %s to run the live catalog tests", liveURLEnv)
	}
	conn, err := query.OpenPostgres(ctx, url)
	if err != nil {
		t.Fatalf("open %s: %v", liveURLEnv, err)
	}
	return conn
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func findForeignKey(t *Table, name string) *ForeignKey {
	for i := range t.ForeignKeys {
		if t.ForeignKeys[i].Name == name {
			return &t.ForeignKeys[i]
		}
	}
	return &ForeignKey{}
}

func findFunction(s *Schema, name string) *Function {
	for i := range s.Functions {
		if s.Functions[i].Name == name {
			return &s.Functions[i]
		}
	}
	return nil
}
